import { useState, useEffect, useCallback } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import {
  Activity, AlertTriangle, Shield, Zap, Clock, Check,
  X, Download, Copy, RefreshCw, FileText, Search,
} from 'lucide-react';
import TopBar       from '../components/TopBar.jsx';
import SeverityBadge from '../components/SeverityBadge.jsx';
import StatusBadge  from '../components/StatusBadge.jsx';
import StatCard     from '../components/StatCard.jsx';
import { ATTACK_SIM_EVENTS, MITRE_COVERAGE } from '../lib/data.js';
import { useBreakpoint } from '../lib/hooks.js';

const TIMELINE_BASE = [
  {t:'06:00',v:1},{t:'06:30',v:0},{t:'07:00',v:2},{t:'07:30',v:1},
  {t:'08:00',v:3},{t:'08:30',v:5},{t:'09:00',v:7},{t:'09:30',v:4},
  {t:'10:00',v:2},{t:'10:30',v:3},{t:'11:00',v:6},{t:'11:30',v:8},
];

function generateReport(inc, now) {
  if (!inc) return '';
  const det = inc.detectedAt ? new Date(inc.detectedAt) : now;
  const ico  = new Date(det.getTime() + 72 * 3600000);
  const ncsc = new Date(det.getTime() + 24 * 3600000);
  const fmt = d => d.toLocaleString('en-GB', { timeZone:'Europe/London', day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' });
  const lines = [];
  const add = s => lines.push(s);

  add('RETAILSHIELD — INCIDENT REPORT');
  add(`Generated: ${fmt(now)}  |  Classification: CONFIDENTIAL`);
  add('─'.repeat(60));
  add('\n§1  EXECUTIVE SUMMARY');
  add(`Incident ID  : ${inc.id}`);
  add(`Title        : ${inc.title}`);
  add(`Severity     : ${inc.severity}`);
  add(`MITRE Tactic : ${inc.tactic} (${inc.technique})`);
  add(`Status       : ${inc.status}`);
  add(`Detected     : ${inc.detectedAt ? fmt(new Date(inc.detectedAt)) : 'During simulation'}`);
  add(`MTTD         : ${inc.mttd} minutes`);
  add(`\n${inc.description}`);

  add('\n§2  TIMELINE OF EVENTS');
  (inc.timeline || []).forEach(e => add(`  ${e.time.padEnd(8)} ${e.event}`));

  add('\n§3  AFFECTED SYSTEMS & DATA');
  (inc.affectedEntities || []).forEach(e => add(`  • ${e}`));
  if (inc.dataCategories?.length) {
    add('\nData categories potentially involved:');
    inc.dataCategories.forEach(d => add(`  • ${d}`));
  }
  add(`\nImpact level: ${inc.impactLevel || 'Under assessment'}`);

  add('\n§4  TECHNICAL ANALYSIS');
  add(`Attack technique: ${inc.technique} — ${inc.tactic}`);
  if (inc.sourceIP)       add(`Source IP      : ${inc.sourceIP} (${inc.country || 'Unknown'})`);
  if (inc.sourceEmail)    add(`Source email   : ${inc.sourceEmail}`);
  if (inc.deviceName)     add(`Affected device: ${inc.deviceName}`);
  if (inc.failedAttempts) add(`Failed attempts: ${inc.failedAttempts.toLocaleString()}`);
  if (inc.filesModified)  add(`Files modified : ${inc.filesModified.toLocaleString()}`);
  add('\nAutomated defences activated:');
  (inc.autoDefence || []).forEach(d => add(`  [+] ${d}`));

  add('\n§5  REGULATORY NOTIFICATIONS');
  if (!inc.needsICO && !inc.needsNCSC) {
    add('No mandatory regulatory notification required based on current assessment.');
  }
  if (inc.needsICO) {
    add('\nICO NOTIFICATION — UK GDPR Article 33 (72-hour obligation)');
    add(`Deadline     : ${fmt(ico)}`);
    add(`Portal       : https://ico.org.uk/for-organisations/report-a-breach/`);
    add(`\nDRAFT: We are notifying the ICO of a personal data breach affecting`);
    add(`${inc.dataCategories?.join(', ') || 'personal data'} in connection with ${inc.id}.`);
    add(`The breach was detected on ${fmt(det)}. Containment measures are in place.`);
  }
  if (inc.needsNCSC) {
    add('\nNCSC REPORT — Cyber Security and Resilience Bill 2025 (24-hour obligation)');
    add(`Deadline     : ${fmt(ncsc)}`);
    add(`Portal       : https://report.ncsc.gov.uk/`);
    add(`\nDRAFT: Reporting incident ${inc.id} — "${inc.title}" detected ${fmt(det)}.`);
    add(`MITRE technique: ${inc.technique} (${inc.tactic}). Impact: ${inc.impactLevel || 'Under assessment'}.`);
  }

  add('\n§6  RECOMMENDED ACTIONS');
  (inc.recommendations || []).forEach((r, i) => add(`  ${i + 1}. ${r}`));

  add('\n' + '─'.repeat(60));
  add('Report generated by RetailShield · ShieldTech Ltd · Tanvir Farhad');
  add('DOI: https://doi.org/10.5281/zenodo.20608262');
  return lines.join('\n');
}

export default function ThreatDetection({ onBack, nav, incidents, setIncidents }) {
  const [view, setView]           = useState('dashboard');
  const [simulating, setSimulating] = useState(false);
  const [selected, setSelected]   = useState(null);
  const [reportInc, setReportInc] = useState(null);
  const [reportText, setReportText] = useState('');
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied]       = useState(false);
  const [clock, setClock]         = useState(new Date());
  const [search, setSearch]       = useState('');
  const [sevFilter, setSevFilter] = useState('All');
  const { isMobile } = useBreakpoint();

  useEffect(() => {
    const t = setInterval(() => setClock(new Date()), 1000);
    return () => clearInterval(t);
  }, []);

  const runSim = useCallback(() => {
    if (simulating) return;
    setSimulating(true);
    ATTACK_SIM_EVENTS.forEach((evt, i) => {
      setTimeout(() => {
        setIncidents(prev => {
          if (prev.find(x => x.id === evt.id)) return prev;
          return [{ ...evt, detectedAt: new Date().toISOString() }, ...prev];
        });
        if (i === ATTACK_SIM_EVENTS.length - 1) setSimulating(false);
      }, (i + 1) * 800);
    });
  }, [simulating, setIncidents]);

  const handleGenerate = () => {
    if (!reportInc) return;
    setGenerating(true); setReportText('');
    setTimeout(() => { setReportText(generateReport(reportInc, clock)); setGenerating(false); }, 1100);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
  };

  const handleDownload = () => {
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([reportText], { type:'text/plain' })),
      download: `RetailShield-${reportInc?.id || 'report'}-${Date.now()}.txt`,
    });
    a.click();
  };

  const active   = incidents.filter(i => i.status === 'Active').length;
  const critical = incidents.filter(i => i.severity === 'Critical').length;

  const filtered = incidents.filter(i => {
    const q = search.toLowerCase();
    return (!search || i.title.toLowerCase().includes(q) || i.id.toLowerCase().includes(q))
      && (sevFilter === 'All' || i.severity === sevFilter);
  });

  const TABS = [
    { id:'dashboard', label:'Dashboard' },
    { id:'incidents', label:`Incidents (${incidents.length})` },
    { id:'report',    label:'AI Report' },
  ];

  return (
    <div style={{ minHeight:'100vh', background:'var(--bg)', display:'flex', flexDirection:'column' }}>
      <TopBar moduleName="Threat Detection" onBack={onBack} nav={nav} currentRoute="threat" />

      {/* Sub-nav */}
      <div style={{ background:'var(--surface)', borderBottom:'1px solid var(--border)', display:'flex', alignItems:'stretch', overflowX:'auto' }}>
        <div style={{ display:'flex', flexShrink:0 }}>
          {TABS.map(tab => (
            <button key={tab.id} onClick={() => { setView(tab.id); setSelected(null); }}
              style={{
                padding:`10px ${isMobile ? '12px' : '16px'}`, background:'none', border:'none',
                borderBottom: view === tab.id ? '2px solid var(--primary)' : '2px solid transparent',
                color: view === tab.id ? 'var(--text)' : 'var(--text-muted)',
                fontSize: isMobile ? '12px' : '13px', fontWeight: view === tab.id ? 600 : 400,
                cursor:'pointer', transition:'color var(--t)', whiteSpace:'nowrap',
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <div style={{ marginLeft:'auto', display:'flex', alignItems:'center', gap:'8px', padding:'6px 12px', flexShrink:0 }}>
          {!isMobile && (
            <div style={{ display:'flex', alignItems:'center', gap:'5px' }}>
              <span className="live-dot" />
              <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)' }}>{clock.toLocaleTimeString('en-GB')}</span>
            </div>
          )}
          <button onClick={runSim} disabled={simulating}
            style={{
              display:'flex', alignItems:'center', gap:'5px',
              padding:'6px 12px', borderRadius:'var(--r-btn)',
              background: simulating ? 'rgba(220,38,38,0.5)' : 'var(--accent)',
              border:'none', color:'white', fontSize:'12px', fontWeight:600,
              cursor: simulating ? 'not-allowed' : 'pointer', transition:'background var(--t)',
              minHeight:'32px', whiteSpace:'nowrap',
            }}
          >
            <Zap size={13} />
            {isMobile ? (simulating ? '…' : 'Attack') : (simulating ? 'Simulating…' : 'Simulate Attack')}
          </button>
        </div>
      </div>

      {/* Content area */}
      <div className="rs-page" style={{ flex:1, overflowY:'auto' }}>
        <div className="rs-page-inner" style={{ margin:'0 auto', display:'flex', flexDirection:'column', gap:'16px' }}>

          {/* ── DASHBOARD ── */}
          {view === 'dashboard' && (
            <div className="anim-fade" style={{ display:'flex', flexDirection:'column', gap:'16px' }}>
              <div className="rs-stats">
                <StatCard label="Active Incidents" value={active}    sub="requiring attention"  accent={active > 0 ? 'var(--accent)' : undefined}    icon={AlertTriangle} />
                <StatCard label="Critical Threats"  value={critical}  sub="this session"         accent={critical > 0 ? '#F97316' : undefined}          icon={Shield} />
                <StatCard label="Avg MTTD"          value="22.5 min"  sub="mean time to detect"  icon={Clock} />
                <StatCard label="Rules Active"      value="19"        sub="MITRE ATT&CK mapped"  icon={Activity} />
              </div>

              <div className="rs-two-col">
                {/* Live feed */}
                <div style={{ background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', overflow:'hidden', display:'flex', flexDirection:'column' }}>
                  <div style={{ padding:'14px 16px', borderBottom:'1px solid var(--border)', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
                    <div style={{ display:'flex', alignItems:'center', gap:'7px' }}>
                      <span className="live-dot" />
                      <span style={{ fontSize:'13px', fontWeight:600, color:'var(--text)' }}>Live Threat Feed</span>
                    </div>
                    <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)' }}>{incidents.length} events</span>
                  </div>
                  <div style={{ maxHeight:'320px', overflowY:'auto' }}>
                    {incidents.length === 0
                      ? <EmptyState msg="No incidents detected" />
                      : incidents.slice(0, 10).map(inc => (
                        <button key={inc.id} onClick={() => { setSelected(inc); setView('incidents'); }}
                          style={{ width:'100%', padding:'10px 16px', background:'none', border:'none', borderBottom:'1px solid var(--border)', cursor:'pointer', textAlign:'left', transition:'background var(--t)' }}
                          onMouseEnter={e => e.currentTarget.style.background='var(--card-hover)'}
                          onMouseLeave={e => e.currentTarget.style.background='none'}
                        >
                          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', gap:'8px', marginBottom:'4px' }}>
                            <span style={{ fontSize:'13px', fontWeight:500, color:'var(--text)', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', flex:1 }}>{inc.title}</span>
                            <SeverityBadge severity={inc.severity} />
                          </div>
                          <div style={{ display:'flex', gap:'10px' }}>
                            <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)' }}>{inc.id}</span>
                            <StatusBadge status={inc.status} />
                          </div>
                        </button>
                      ))}
                    {incidents.length > 10 && (
                      <button onClick={() => setView('incidents')} style={{ width:'100%', padding:'10px', background:'none', border:'none', borderTop:'1px solid var(--border)', color:'var(--primary)', fontSize:'12px', cursor:'pointer', fontWeight:500 }}>
                        View all {incidents.length} incidents
                      </button>
                    )}
                  </div>
                </div>

                {/* MITRE coverage */}
                <div style={{ background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', overflow:'hidden' }}>
                  <div style={{ padding:'14px 16px', borderBottom:'1px solid var(--border)' }}>
                    <span style={{ fontSize:'13px', fontWeight:600, color:'var(--text)' }}>MITRE ATT&CK Coverage</span>
                  </div>
                  <div className="rs-mitre">
                    {MITRE_COVERAGE.map(m => {
                      const pct = m.covered / m.total;
                      const col = pct >= 0.6 ? 'var(--success)' : pct >= 0.3 ? 'var(--warning)' : 'var(--accent)';
                      return (
                        <div key={m.tactic} style={{ background:'var(--surface)', borderRadius:'6px', padding:'9px 11px' }}>
                          <div style={{ display:'flex', justifyContent:'space-between', marginBottom:'5px', gap:'4px' }}>
                            <span style={{ fontSize:'11px', color:'var(--text-muted)', fontWeight:500, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', flex:1 }}>{m.tactic}</span>
                            <span style={{ fontSize:'11px', color:col, fontFamily:'var(--font-mono)', fontWeight:600, flexShrink:0 }}>{m.covered}/{m.total}</span>
                          </div>
                          <div style={{ height:'3px', background:'var(--border)', borderRadius:'2px', overflow:'hidden' }}>
                            <div style={{ height:'100%', width:`${pct*100}%`, background:col, borderRadius:'2px' }} />
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>

              {/* Timeline chart */}
              <div style={{ background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', padding:'16px' }}>
                <div style={{ display:'flex', justifyContent:'space-between', marginBottom:'12px' }}>
                  <span style={{ fontSize:'13px', fontWeight:600, color:'var(--text)' }}>Alert Timeline — Today</span>
                  <span style={{ fontSize:'11px', color:'var(--text-dim)' }}>30-min intervals</span>
                </div>
                <ResponsiveContainer width="100%" height={140}>
                  <BarChart data={TIMELINE_BASE} margin={{ top:4, right:4, left:-24, bottom:0 }}>
                    <XAxis dataKey="t" tick={{ fontSize:10, fill:'#5A6478' }} axisLine={false} tickLine={false} interval={isMobile ? 2 : 1} />
                    <YAxis tick={{ fontSize:10, fill:'#5A6478' }} axisLine={false} tickLine={false} width={32} />
                    <Tooltip contentStyle={{ background:'var(--card)', border:'1px solid var(--border)', borderRadius:'6px', fontSize:'12px' }} labelStyle={{ color:'var(--text-muted)' }} itemStyle={{ color:'var(--primary)' }} />
                    <Bar dataKey="v" radius={[3,3,0,0]}>
                      {TIMELINE_BASE.map((d,i) => <Cell key={i} fill={d.v>=6?'#DC2626':d.v>=4?'#D97706':'#2563EB'} opacity={0.8} />)}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {/* ── INCIDENTS ── */}
          {view === 'incidents' && (
            <div className="anim-fade" style={{ display:'flex', flexDirection: isMobile || !selected ? 'column' : 'row', gap:'16px' }}>

              {/* Table panel */}
              <div style={{ flex:1, background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', overflow:'hidden', minWidth:0 }}>
                {/* Filters */}
                <div style={{ padding:'12px 16px', borderBottom:'1px solid var(--border)', display:'flex', gap:'8px', flexWrap:'wrap' }}>
                  <div style={{ position:'relative', flex:1, minWidth:'140px' }}>
                    <Search size={13} color="var(--text-dim)" style={{ position:'absolute', left:'9px', top:'50%', transform:'translateY(-50%)' }} />
                    <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search…"
                      style={{ width:'100%', padding:'7px 9px 7px 28px', background:'var(--surface)', border:'1px solid var(--border)', borderRadius:'var(--r-btn)', color:'var(--text)', fontSize:'14px', outline:'none' }} />
                  </div>
                  <div style={{ display:'flex', gap:'4px', flexWrap:'wrap' }}>
                    {['All','Critical','High','Medium','Low'].map(s => (
                      <button key={s} onClick={() => setSevFilter(s)} style={{ padding:'5px 10px', borderRadius:'var(--r-btn)', border:'1px solid var(--border)', background: sevFilter===s?'var(--primary)':'var(--surface)', color: sevFilter===s?'white':'var(--text-muted)', fontSize:'11px', fontWeight:500, cursor:'pointer', transition:'all var(--t)', minHeight:'32px' }}>{s}</button>
                    ))}
                  </div>
                </div>

                {/* Table — scrollable on mobile */}
                <div className="rs-table-wrap">
                  <div data-table style={{ minWidth:'560px' }}>
                    <div style={{ display:'grid', gridTemplateColumns:'80px 1fr 90px 110px 60px', padding:'9px 16px', background:'var(--surface)', borderBottom:'1px solid var(--border)' }}>
                      {['ID','Title','Severity','Status','MTTD'].map(h => <span key={h} style={{ fontSize:'11px', fontWeight:600, color:'var(--text-dim)', textTransform:'uppercase', letterSpacing:'0.07em' }}>{h}</span>)}
                    </div>
                    {filtered.length === 0
                      ? <EmptyState msg="No incidents match current filters" />
                      : filtered.map(inc => (
                        <button key={inc.id} onClick={() => setSelected(selected?.id===inc.id ? null : inc)}
                          style={{
                            width:'100%', display:'grid', gridTemplateColumns:'80px 1fr 90px 110px 60px',
                            padding:'11px 16px', background: selected?.id===inc.id?'var(--card-hover)':'none',
                            border:'none', borderBottom:'1px solid var(--border)', cursor:'pointer',
                            textAlign:'left', transition:'background var(--t)', alignItems:'center',
                          }}
                          onMouseEnter={e => { if(selected?.id!==inc.id) e.currentTarget.style.background='rgba(255,255,255,0.02)'; }}
                          onMouseLeave={e => { if(selected?.id!==inc.id) e.currentTarget.style.background='none'; }}
                        >
                          <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)' }}>{inc.id}</span>
                          <span style={{ fontSize:'13px', color:'var(--text)', fontWeight:500, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', paddingRight:'12px' }}>{inc.title}</span>
                          <SeverityBadge severity={inc.severity} />
                          <StatusBadge   status={inc.status} />
                          <span style={{ fontSize:'12px', color:'var(--text-muted)', fontFamily:'var(--font-mono)' }}>{inc.mttd}m</span>
                        </button>
                      ))}
                  </div>
                </div>
              </div>

              {/* Detail panel */}
              {selected && (
                <div style={{ width: isMobile ? '100%' : '380px', background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', overflow:'hidden', animation:'fadeIn 200ms ease', display:'flex', flexDirection:'column', flexShrink:0 }}>
                  <div style={{ padding:'14px 16px', borderBottom:'1px solid var(--border)', display:'flex', justifyContent:'space-between', alignItems:'flex-start', gap:'8px' }}>
                    <div style={{ minWidth:0 }}>
                      <div style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)', marginBottom:'3px' }}>{selected.id}</div>
                      <div style={{ fontSize:'13px', fontWeight:600, color:'var(--text)', lineHeight:1.3 }}>{selected.title}</div>
                    </div>
                    <button onClick={() => setSelected(null)} aria-label="Close" style={{ background:'none', border:'none', color:'var(--text-dim)', cursor:'pointer', padding:'4px', flexShrink:0, minWidth:'32px', minHeight:'32px', display:'flex', alignItems:'center', justifyContent:'center' }}>
                      <X size={15} />
                    </button>
                  </div>
                  <div style={{ flex:1, overflowY:'auto', padding:'14px 16px', display:'flex', flexDirection:'column', gap:'14px' }}>
                    <div style={{ display:'flex', gap:'6px', flexWrap:'wrap' }}>
                      <SeverityBadge severity={selected.severity} size="lg" />
                      <StatusBadge status={selected.status} />
                      <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)', alignSelf:'center' }}>{selected.technique}</span>
                    </div>
                    <p style={{ fontSize:'13px', color:'var(--text-muted)', lineHeight:1.6 }}>{selected.description}</p>

                    <Sect title="Timeline">
                      {(selected.timeline||[]).map((e,i) => (
                        <div key={i} style={{ display:'flex', gap:'10px', paddingBottom:'6px' }}>
                          <span style={{ fontSize:'11px', color:'var(--primary)', fontFamily:'var(--font-mono)', flexShrink:0 }}>{e.time}</span>
                          <span style={{ fontSize:'12px', color:'var(--text-muted)' }}>{e.event}</span>
                        </div>
                      ))}
                    </Sect>

                    <Sect title="Automated Defence">
                      {(selected.autoDefence||[]).map((d,i) => (
                        <div key={i} style={{ display:'flex', gap:'7px', marginBottom:'4px' }}>
                          <Check size={12} color="var(--success)" style={{ flexShrink:0, marginTop:'2px' }} />
                          <span style={{ fontSize:'12px', color:'var(--text-muted)' }}>{d}</span>
                        </div>
                      ))}
                    </Sect>

                    <Sect title="Recommendations">
                      {(selected.recommendations||[]).map((r,i) => (
                        <div key={i} style={{ display:'flex', gap:'7px', marginBottom:'4px' }}>
                          <span style={{ fontSize:'11px', color:'var(--text-dim)', fontFamily:'var(--font-mono)', flexShrink:0 }}>{i+1}.</span>
                          <span style={{ fontSize:'12px', color:'var(--text-muted)' }}>{r}</span>
                        </div>
                      ))}
                    </Sect>

                    {(selected.needsICO || selected.needsNCSC) && (
                      <div style={{ background:'var(--accent-dim)', border:'1px solid rgba(220,38,38,0.25)', borderRadius:'6px', padding:'10px 12px' }}>
                        <div style={{ fontSize:'12px', fontWeight:600, color:'#F87171', marginBottom:'6px' }}>Regulatory Notification Required</div>
                        <div style={{ display:'flex', gap:'6px', flexWrap:'wrap' }}>
                          {selected.needsICO  && <span style={{ fontSize:'11px', background:'rgba(220,38,38,0.1)', color:'#F87171', padding:'2px 8px', borderRadius:'4px', border:'1px solid rgba(220,38,38,0.2)' }}>ICO — 72h</span>}
                          {selected.needsNCSC && <span style={{ fontSize:'11px', background:'rgba(220,38,38,0.1)', color:'#F87171', padding:'2px 8px', borderRadius:'4px', border:'1px solid rgba(220,38,38,0.2)' }}>NCSC — 24h</span>}
                        </div>
                      </div>
                    )}

                    <button onClick={() => { setReportInc(selected); setView('report'); setReportText(''); }}
                      style={{ display:'flex', alignItems:'center', justifyContent:'center', gap:'6px', padding:'10px', borderRadius:'var(--r-btn)', background:'var(--primary)', border:'none', color:'white', fontSize:'13px', fontWeight:600, cursor:'pointer', transition:'background var(--t)', minHeight:'44px' }}
                      onMouseEnter={e => e.currentTarget.style.background='var(--primary-dk)'}
                      onMouseLeave={e => e.currentTarget.style.background='var(--primary)'}
                    >
                      <FileText size={14} /> Generate AI Report
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── AI REPORT ── */}
          {view === 'report' && (
            <div className="anim-fade" style={{ maxWidth:'860px' }}>
              <div style={{ background:'var(--card)', border:'1px solid var(--border)', borderRadius:'var(--r-card)', overflow:'hidden' }}>
                <div style={{ padding:'18px 20px', borderBottom:'1px solid var(--border)' }}>
                  <div style={{ fontSize:'14px', fontWeight:600, color:'var(--text)', marginBottom:'3px' }}>AI Incident Report Generator</div>
                  <div style={{ fontSize:'12px', color:'var(--text-dim)' }}>6-section structured report with ICO/NCSC draft notifications where required.</div>
                </div>
                <div style={{ padding:'16px 20px', borderBottom:'1px solid var(--border)', display:'flex', gap:'10px', flexWrap:'wrap', alignItems:'flex-end' }}>
                  <div style={{ flex:1, minWidth:'180px' }}>
                    <label style={{ fontSize:'12px', fontWeight:500, color:'var(--text-muted)', display:'block', marginBottom:'5px' }}>Select incident</label>
                    <select value={reportInc?.id||''} onChange={e => { setReportInc(incidents.find(i=>i.id===e.target.value)||null); setReportText(''); }}
                      style={{ width:'100%', padding:'8px 10px', background:'var(--surface)', border:'1px solid var(--border)', borderRadius:'var(--r-btn)', color:'var(--text)', fontSize:'14px', cursor:'pointer', outline:'none' }}>
                      <option value="">— choose an incident —</option>
                      {incidents.map(i => <option key={i.id} value={i.id}>{i.id} — {i.title}</option>)}
                    </select>
                  </div>
                  <button onClick={handleGenerate} disabled={!reportInc||generating}
                    style={{
                      display:'flex', alignItems:'center', gap:'6px', padding:'9px 16px', borderRadius:'var(--r-btn)',
                      background: !reportInc||generating?'rgba(37,99,235,0.5)':'var(--primary)',
                      border:'none', color:'white', fontSize:'13px', fontWeight:600,
                      cursor: !reportInc||generating?'not-allowed':'pointer', transition:'background var(--t)',
                      minHeight:'40px', whiteSpace:'nowrap',
                    }}
                    onMouseEnter={e => { if(reportInc&&!generating) e.currentTarget.style.background='var(--primary-dk)'; }}
                    onMouseLeave={e => { if(reportInc&&!generating) e.currentTarget.style.background='var(--primary)'; }}
                  >
                    {generating?<><Spinner/>Generating…</>:<><RefreshCw size={13}/>Generate Report</>}
                  </button>
                </div>
                {reportText && (
                  <>
                    <div style={{ padding:'6px 20px', background:'var(--surface)', borderBottom:'1px solid var(--border)', display:'flex', gap:'8px', justifyContent:'flex-end' }}>
                      <SmallBtn onClick={handleCopy}>{copied?<><Check size={12} color="var(--success)"/>Copied</>:<><Copy size={12}/>Copy</>}</SmallBtn>
                      <SmallBtn onClick={handleDownload}><Download size={12}/>Download</SmallBtn>
                    </div>
                    <pre style={{ padding:'20px', fontSize:'12px', lineHeight:1.7, color:'var(--text-muted)', fontFamily:'var(--font-mono)', whiteSpace:'pre-wrap', wordBreak:'break-word', maxHeight:'560px', overflowY:'auto', margin:0, background:'var(--surface)', animation:'fadeIn 300ms ease' }}>
                      {reportText}
                    </pre>
                  </>
                )}
                {!reportText&&!generating&&<EmptyState msg="Select an incident and click Generate Report" />}
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}

function Sect({ title, children }) {
  return (
    <div>
      <div style={{ fontSize:'11px', fontWeight:600, color:'var(--text-dim)', textTransform:'uppercase', letterSpacing:'0.07em', marginBottom:'7px' }}>{title}</div>
      {children}
    </div>
  );
}
function EmptyState({ msg }) {
  return <div style={{ padding:'40px', textAlign:'center', color:'var(--text-dim)', fontSize:'13px' }}>{msg}</div>;
}
function Spinner() {
  return <span style={{ width:'12px', height:'12px', border:'2px solid rgba(255,255,255,0.3)', borderTopColor:'white', borderRadius:'50%', animation:'spin 0.7s linear infinite', display:'inline-block', marginRight:'6px' }} />;
}
function SmallBtn({ onClick, children }) {
  return (
    <button onClick={onClick} style={{ display:'flex', alignItems:'center', gap:'4px', padding:'5px 10px', background:'none', border:'1px solid var(--border)', borderRadius:'6px', color:'var(--text-muted)', fontSize:'12px', cursor:'pointer', transition:'all var(--t)', minHeight:'32px' }}
      onMouseEnter={e => e.currentTarget.style.color='var(--text)'}
      onMouseLeave={e => e.currentTarget.style.color='var(--text-muted)'}
    >{children}</button>
  );
}
