/**
 * RetailShield — AI Threat Briefing Endpoint
 * Vercel Serverless Function — POST /api/brief
 * Calls the Anthropic Claude API to generate an executive-ready
 * threat summary from the current dashboard state.
 *
 * Requires ANTHROPIC_API_KEY env var set in Vercel project settings.
 * Falls back to a simulated briefing when the key is absent.
 */

const FALLBACK_BRIEFING = (threats, score, vulnCount) => `
RETAILSHIELD EXECUTIVE THREAT BRIEFING — ${new Date().toUTCString()}

Security Score: ${score}/100 | Active Threats: ${threats.critical} Critical, ${threats.high} High | CVEs Outstanding: ${vulnCount}

IMMEDIATE ACTIONS REQUIRED:
${threats.critical > 0 ? `• ${threats.critical} CRITICAL threat(s) detected — incident response team should be engaged immediately.` : ''}
${threats.active > 0 ? `• ${threats.active} active threat(s) currently uncontained — review live feed for isolation status.` : ''}
${vulnCount > 0 ? `• ${vulnCount} unpatched CVEs identified across retail infrastructure — prioritise critical severity patches within 48 hours.` : ''}

Automated playbooks have been triggered for all active incidents. Manual analyst review required for items marked ACTIVE in the threat feed.

This briefing was generated by RetailShield v2.0 — ShieldTech Ltd.
`.trim()

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { threats = {}, score = 0, vulnSummary = {}, topThreats = [] } = req.body || {}

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    return res.status(200).json({
      briefing: FALLBACK_BRIEFING(threats, score, Object.values(vulnSummary).reduce((a, b) => a + b, 0)),
      source: 'fallback',
    })
  }

  const threatLines = topThreats.slice(0, 5).map(
    (t, i) => `${i + 1}. ${t.name} (${t.mitre} — ${t.tactic}, ${t.severity.toUpperCase()}, Status: ${t.status})`
  ).join('\n')

  const vulnTotal = Object.values(vulnSummary).reduce((a, b) => a + b, 0)

  const prompt = `You are a senior SOC analyst writing a concise executive briefing for a UK retail CISO.

Current RetailShield dashboard state:
- Security Score: ${score}/100
- Active Threats: ${threats.critical || 0} Critical, ${threats.high || 0} High, ${threats.active || 0} Active, ${threats.blocked || 0} Blocked
- CVE Vulnerability Summary: ${vulnSummary.critical || 0} Critical, ${vulnSummary.high || 0} High, ${vulnSummary.medium || 0} Medium
- Total unpatched CVEs: ${vulnTotal}

Top active threats:
${threatLines || 'No active threats at this time.'}

Write a professional executive briefing in exactly this format:
1. One sentence overall status (use plain English, not jargon)
2. Top 2-3 priority actions the business must take RIGHT NOW
3. Regulatory exposure (PCI DSS, UK GDPR Art.33 if relevant)
4. One closing sentence on what automated playbooks have already done

Keep it under 200 words. Be direct and authoritative. Do not use bullet points — use numbered lists only for the priority actions. Do not start with "I" or "As an AI".`

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 400,
        messages: [{ role: 'user', content: prompt }],
      }),
    })

    if (!response.ok) {
      const err = await response.text()
      console.error('Anthropic API error:', err)
      return res.status(200).json({
        briefing: FALLBACK_BRIEFING(threats, score, vulnTotal),
        source: 'fallback',
      })
    }

    const data = await response.json()
    const briefing = data.content?.[0]?.text || FALLBACK_BRIEFING(threats, score, vulnTotal)

    return res.status(200).json({ briefing, source: 'claude' })
  } catch (err) {
    console.error('Brief generation error:', err)
    return res.status(200).json({
      briefing: FALLBACK_BRIEFING(threats, score, vulnTotal),
      source: 'fallback',
    })
  }
}
