import { C } from './tokens.js';

export const DETECTION_RULES = [
  { id: 'DR-001', name: 'Phishing Email Detection',         technique: 'T1566.001', tactic: 'Initial Access',     severity: 'High',     status: 'Active',   file: 'phishing_detection.kql',        lastTriggered: '2 min ago',   triggerCount: 14 },
  { id: 'DR-002', name: 'Ransomware Indicator',             technique: 'T1486',     tactic: 'Impact',            severity: 'Critical', status: 'Active',   file: 'ransomware_indicator.kql',      lastTriggered: '8 min ago',   triggerCount: 3  },
  { id: 'DR-003', name: 'Data Exfiltration',                technique: 'T1048',     tactic: 'Exfiltration',      severity: 'Critical', status: 'Active',   file: 'data_exfiltration.kql',         lastTriggered: '34 min ago',  triggerCount: 7  },
  { id: 'DR-004', name: 'After-Hours System Access',        technique: 'T1078',     tactic: 'Persistence',       severity: 'Medium',   status: 'Active',   file: 'after_hours_access.kql',        lastTriggered: '1 hr ago',    triggerCount: 21 },
  { id: 'DR-005', name: 'Credential Stuffing',              technique: 'T1110.004', tactic: 'Credential Access', severity: 'High',     status: 'Active',   file: 'credential_stuffing.kql',       lastTriggered: '5 min ago',   triggerCount: 89 },
  { id: 'DR-006', name: 'SQL Injection Attempt',            technique: 'T1190',     tactic: 'Initial Access',    severity: 'High',     status: 'Active',   file: 'sql_injection.kql',             lastTriggered: '12 min ago',  triggerCount: 44 },
  { id: 'DR-007', name: 'Lateral Movement – PtH',          technique: 'T1550.002', tactic: 'Lateral Movement',  severity: 'Critical', status: 'Active',   file: 'lateral_movement.kql',          lastTriggered: '3 hr ago',    triggerCount: 2  },
  { id: 'DR-008', name: 'Privilege Escalation',             technique: 'T1068',     tactic: 'Privilege Escalation', severity: 'High',  status: 'Active',   file: 'priv_escalation.kql',           lastTriggered: '47 min ago',  triggerCount: 9  },
  { id: 'DR-009', name: 'POS Malware Detected',             technique: 'T1055',     tactic: 'Defence Evasion',   severity: 'Critical', status: 'Active',   file: 'pos_malware.kql',               lastTriggered: '1 hr ago',    triggerCount: 1  },
  { id: 'DR-010', name: 'Suspicious PowerShell',            technique: 'T1059.001', tactic: 'Execution',         severity: 'High',     status: 'Active',   file: 'suspicious_powershell.kql',     lastTriggered: '28 min ago',  triggerCount: 17 },
  { id: 'DR-011', name: 'Anomalous Network Traffic',        technique: 'T1071',     tactic: 'C2',                severity: 'Medium',   status: 'Active',   file: 'anomalous_network.kql',         lastTriggered: '6 min ago',   triggerCount: 56 },
  { id: 'DR-012', name: 'Impossible Travel Login',          technique: 'T1078',     tactic: 'Initial Access',    severity: 'High',     status: 'Active',   file: 'impossible_travel.kql',         lastTriggered: '2 hr ago',    triggerCount: 4  },
  { id: 'DR-013', name: 'USB Mass Storage Insert',          technique: 'T1091',     tactic: 'Initial Access',    severity: 'Medium',   status: 'Active',   file: 'usb_insert.kql',                lastTriggered: '4 hr ago',    triggerCount: 11 },
  { id: 'DR-014', name: 'DNS Tunnelling',                   technique: 'T1071.004', tactic: 'C2',                severity: 'High',     status: 'Active',   file: 'dns_tunnel.kql',                lastTriggered: '19 min ago',  triggerCount: 6  },
  { id: 'DR-015', name: 'Supply Chain Compromise',          technique: 'T1195',     tactic: 'Initial Access',    severity: 'Critical', status: 'Active',   file: 'supply_chain.kql',              lastTriggered: '5 hr ago',    triggerCount: 1  },
  { id: 'DR-016', name: 'Brute Force – Admin Panel',        technique: 'T1110.001', tactic: 'Credential Access', severity: 'High',     status: 'Active',   file: 'brute_force_admin.kql',         lastTriggered: '9 min ago',   triggerCount: 33 },
  { id: 'DR-017', name: 'Scheduled Task Creation',          technique: 'T1053.005', tactic: 'Persistence',       severity: 'Medium',   status: 'Active',   file: 'scheduled_task.kql',            lastTriggered: '2 hr ago',    triggerCount: 8  },
  { id: 'DR-018', name: 'LSASS Memory Access',              technique: 'T1003.001', tactic: 'Credential Access', severity: 'Critical', status: 'Active',   file: 'lsass_access.kql',              lastTriggered: '6 hr ago',    triggerCount: 2  },
  { id: 'DR-019', name: 'Malicious Macro in Office File',   technique: 'T1566.001', tactic: 'Initial Access',    severity: 'High',     status: 'Disabled', file: 'office_macro.kql',              lastTriggered: 'Never',       triggerCount: 0  },
];

export const MITRE_COVERAGE = [
  { tactic: 'Initial Access',        covered: 5, total: 9  },
  { tactic: 'Execution',             covered: 2, total: 5  },
  { tactic: 'Persistence',           covered: 3, total: 7  },
  { tactic: 'Privilege Escalation',  covered: 2, total: 8  },
  { tactic: 'Defence Evasion',       covered: 3, total: 11 },
  { tactic: 'Credential Access',     covered: 4, total: 9  },
  { tactic: 'Discovery',             covered: 1, total: 7  },
  { tactic: 'Lateral Movement',      covered: 2, total: 4  },
  { tactic: 'Collection',            covered: 1, total: 5  },
  { tactic: 'C2',                    covered: 3, total: 6  },
  { tactic: 'Exfiltration',          covered: 2, total: 4  },
  { tactic: 'Impact',                covered: 2, total: 7  },
];

export const BASELINE_INCIDENTS = [
  {
    id: 'INC-2847', title: 'Credential Stuffing Campaign',
    severity: 'High', tactic: 'Credential Access', technique: 'T1110.004',
    status: 'Investigating', detectedAt: '2026-06-08T09:14:00Z', mttd: 3,
    entity: 'ecom-portal.retailshield.io', sourceIP: '185.220.101.47',
    country: 'Russia', failedAttempts: 1847,
    description: 'Distributed credential stuffing campaign targeting the e-commerce customer portal using breached credential pairs sourced from dark web marketplaces.',
    timeline: [
      { time: '09:11', event: 'First failed login attempt from 185.220.101.47' },
      { time: '09:14', event: 'Alert triggered — 1,847 failed attempts in 15 minutes' },
      { time: '09:16', event: 'IP blocked via automated playbook (block_ip)' },
      { time: '09:22', event: 'SOC analyst began investigation' },
    ],
    affectedEntities: ['ecom-portal.retailshield.io', '185.220.101.47', 'Customer Portal DB'],
    autoDefence: ['Source IP blocked at perimeter firewall', 'Rate limiting applied to /login endpoint', 'CAPTCHA enforcement enabled'],
    recommendations: ['Enable MFA for all customer accounts', 'Implement credential breach monitoring', 'Review and rotate compromised credentials'],
  },
  {
    id: 'INC-2846', title: 'Phishing Email — Invoice Lure',
    severity: 'High', tactic: 'Initial Access', technique: 'T1566.001',
    status: 'Contained', detectedAt: '2026-06-08T08:42:00Z', mttd: 5,
    entity: 'finance@retailshield.io', sourceEmail: 'supplier-invoices@dr4gonmail.com',
    attachmentType: 'docm', phishingScore: 94,
    description: 'Spearphishing email with malicious Word macro attachment delivered to Finance team, spoofing a known supplier domain.',
    timeline: [
      { time: '08:37', event: 'Email received at finance@retailshield.io from dr4gonmail.com' },
      { time: '08:42', event: 'Phishing score 94/100 triggered alert (threshold: 70)' },
      { time: '08:43', event: 'Email quarantined automatically' },
      { time: '08:55', event: 'Attachment analysed — embedded macro with C2 beacon payload' },
    ],
    affectedEntities: ['finance@retailshield.io', 'Finance Department', 'Email Gateway'],
    autoDefence: ['Email quarantined', 'Sender domain blocked', 'Attachment hash added to blocklist'],
    recommendations: ['Conduct phishing awareness training for Finance team', 'Strengthen DMARC/DKIM enforcement', 'Enable macro execution policy via GPO'],
  },
  {
    id: 'INC-2845', title: 'After-Hours POS Access',
    severity: 'Medium', tactic: 'Persistence', technique: 'T1078',
    status: 'Resolved', detectedAt: '2026-06-08T02:17:00Z', mttd: 12,
    entity: 'Store-042', operatorName: 'J. Martins',
    systemAccessed: 'POS', suspicionScore: 72,
    description: 'Employee accessed POS system at Store-042 at 02:17 AM, outside configured operational hours (06:00–22:00).',
    timeline: [
      { time: '02:17', event: 'POS login by J. Martins — outside configured hours' },
      { time: '02:29', event: 'Alert triggered — IsAfterHours flag set' },
      { time: '03:15', event: 'SOC notified store manager' },
      { time: '09:00', event: 'Manager confirmed authorised for stock take — resolved' },
    ],
    affectedEntities: ['Store-042 POS Terminal', 'J. Martins (Employee ID: EMP-3821)'],
    autoDefence: ['SOC notification sent', 'Session flagged for review'],
    recommendations: ['Update after-hours access schedule for planned stock takes', 'Implement manager pre-approval workflow for out-of-hours access'],
  },
];

export const ATTACK_SIM_EVENTS = [
  {
    id: 'INC-2850',
    title: 'DragonForce Ransomware — WAREHOUSE-DC01',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1486',
    status: 'Active',
    detectedAt: null,
    mttd: 2,
    entity: 'WAREHOUSE-DC01',
    deviceName: 'WAREHOUSE-DC01',
    filesModified: 847,
    suspiciousExtension: '.dragon',
    ransomwareFamily: 'DragonForce',
    suspicionScore: 99,
    description: 'DragonForce ransomware detected on warehouse domain controller. 847 files encrypted within 2 minutes of initial execution. Matching M&S supply-chain attack TTP (June 2025).',
    timeline: [
      { time: '+0:00', event: 'Ransomware binary executed on WAREHOUSE-DC01' },
      { time: '+0:02', event: '847 files renamed to .dragon extension' },
      { time: '+0:02', event: 'Alert triggered — FilesModified_d = 847 (threshold: 100)' },
      { time: '+0:03', event: 'Automated endpoint isolation initiated' },
    ],
    affectedEntities: ['WAREHOUSE-DC01', 'Warehouse File Share', 'Domain Controller'],
    autoDefence: ['Endpoint isolated from network', 'Domain admin accounts locked', 'Backup snapshot initiated'],
    recommendations: ['Engage incident response team immediately', 'Notify NCSC within 24 hours (CSR Bill 2025)', 'Notify ICO within 72 hours if personal data affected', 'Assess backup integrity before restoration'],
    needsICO: true,
    needsNCSC: true,
    impactLevel: 'Severe',
    dataCategories: ['Operational Data', 'Employee Records'],
  },
  {
    id: 'INC-2851',
    title: 'Mass Data Exfiltration — 1.2 TB to External IP',
    severity: 'Critical',
    tactic: 'Exfiltration',
    technique: 'T1048',
    status: 'Active',
    detectedAt: null,
    mttd: 4,
    entity: 'ERP-SERVER-01',
    destinationIP: '91.108.4.177',
    destinationPort: 4444,
    dataTransferredMB: 1228,
    geoLocation: 'Russia',
    suspicionScore: 95,
    description: '1.2 TB of data transferred to a Russian-registered IP on port 4444. Data includes customer PII and payment records from ERP system. Possible exfiltration prior to ransomware deployment.',
    timeline: [
      { time: '+0:00', event: 'Outbound connection established to 91.108.4.177:4444' },
      { time: '+0:04', event: '1,228 MB transferred — alert threshold (100 MB) exceeded' },
      { time: '+0:04', event: 'Alert triggered — SuspicionScore_d = 95' },
      { time: '+0:05', event: 'Outbound connection blocked at firewall' },
    ],
    affectedEntities: ['ERP-SERVER-01', '91.108.4.177 (Russia)', 'Customer Database'],
    autoDefence: ['Outbound connection terminated', 'Destination IP added to blocklist', 'DLP policy enforced'],
    recommendations: ['Conduct forensic analysis of ERP-SERVER-01', 'Notify ICO within 72 hours — customer PII likely exfiltrated', 'Engage legal team for breach assessment', 'Review all outbound connections in past 7 days'],
    needsICO: true,
    needsNCSC: true,
    impactLevel: 'Critical',
    dataCategories: ['Customer PII', 'Payment Records', 'Employee Data'],
  },
  {
    id: 'INC-2852',
    title: 'Credential Stuffing — 3,200 Attempts',
    severity: 'High',
    tactic: 'Credential Access',
    technique: 'T1110.004',
    status: 'Active',
    detectedAt: null,
    mttd: 3,
    entity: 'ecom-portal.retailshield.io',
    sourceIP: '185.220.101.52',
    failedAttempts: 3200,
    geoLocation: 'Romania',
    suspicionScore: 90,
    description: 'High-volume credential stuffing attack against customer portal. 3,200 failed login attempts from Romanian IP in 8 minutes using known breached credential pairs.',
    timeline: [
      { time: '+0:00', event: 'Credential stuffing campaign begins from 185.220.101.52' },
      { time: '+0:03', event: 'Alert triggered — 3,200 failed attempts detected' },
      { time: '+0:04', event: 'IP blocked via automated playbook' },
    ],
    affectedEntities: ['ecom-portal.retailshield.io', '185.220.101.52 (Romania)', 'Customer Auth Service'],
    autoDefence: ['Source IP blocked', 'Rate limiting enforced', 'CAPTCHA challenge activated'],
    recommendations: ['Force password reset for potentially affected accounts', 'Enable breach credential monitoring', 'Implement device fingerprinting'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: [],
  },
  {
    id: 'INC-2853',
    title: 'Spearphishing — Finance CFO Targeted',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1566.001',
    status: 'Investigating',
    detectedAt: null,
    mttd: 5,
    entity: 'cfo@retailshield.io',
    sourceEmail: 'board-update@retailshield-plc.co.uk',
    attachmentType: 'xlsm',
    phishingScore: 97,
    description: 'Highly targeted spearphishing email sent to CFO impersonating board communications. XLSM attachment contains obfuscated macro downloading Cobalt Strike beacon.',
    timeline: [
      { time: '+0:00', event: 'Phishing email received at cfo@retailshield.io' },
      { time: '+0:05', event: 'Phishing score 97/100 — immediate quarantine' },
      { time: '+0:06', event: 'Sandbox detonation confirms Cobalt Strike payload' },
    ],
    affectedEntities: ['cfo@retailshield.io', 'Finance Systems', 'Email Gateway'],
    autoDefence: ['Email quarantined', 'Sender domain blocked', 'Macro execution blocked by policy'],
    recommendations: ['Brief CFO on spearphishing TTPs', 'Review email gateway DMARC enforcement', 'Enable advanced threat protection for executive mailboxes'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'High',
    dataCategories: ['Financial Data'],
  },
  {
    id: 'INC-2854',
    title: 'After-Hours ERP Access — Multiple Accounts',
    severity: 'Medium',
    tactic: 'Persistence',
    technique: 'T1078',
    status: 'Investigating',
    detectedAt: null,
    mttd: 8,
    entity: 'ERP-PROD-01',
    operatorName: 'Multiple (4 accounts)',
    systemAccessed: 'ERP',
    suspicionScore: 78,
    description: 'Four employee accounts accessed ERP production system simultaneously at 03:45 AM, outside configured operational hours. Possible insider threat or compromised credentials.',
    timeline: [
      { time: '+0:00', event: '4 concurrent ERP logins at 03:45 AM' },
      { time: '+0:08', event: 'After-hours alert triggered for all 4 accounts' },
      { time: '+0:09', event: 'SOC notification sent to on-call analyst' },
    ],
    affectedEntities: ['ERP-PROD-01', 'Accounts: emp-0192, emp-0341, emp-0088, emp-0612'],
    autoDefence: ['Sessions flagged for review', 'SOC notified', 'Activity logging enhanced'],
    recommendations: ['Interview affected employees', 'Review ERP activity logs for data access', 'Consider suspending accounts pending investigation'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: ['Employee Records', 'Financial Data'],
  },
  {
    id: 'INC-2855',
    title: 'Lateral Movement — Pass-the-Hash Detected',
    severity: 'Critical',
    tactic: 'Lateral Movement',
    technique: 'T1550.002',
    status: 'Active',
    detectedAt: null,
    mttd: 6,
    entity: 'MGMT-SERVER-02',
    sourceHost: 'WAREHOUSE-DC01',
    targetHost: 'MGMT-SERVER-02',
    suspicionScore: 98,
    description: 'Pass-the-hash attack detected moving from compromised WAREHOUSE-DC01 to management server. Attacker using harvested NTLM hashes to authenticate without plaintext credentials.',
    timeline: [
      { time: '+0:00', event: 'Unusual NTLM authentication from WAREHOUSE-DC01 to MGMT-SERVER-02' },
      { time: '+0:06', event: 'Pass-the-hash pattern detected — alert triggered' },
      { time: '+0:07', event: 'Network segmentation enforced between segments' },
    ],
    affectedEntities: ['WAREHOUSE-DC01', 'MGMT-SERVER-02', 'Active Directory'],
    autoDefence: ['Network segment isolated', 'Affected accounts locked', 'Credential reset initiated'],
    recommendations: ['Reset all admin credentials across the domain', 'Enable Protected Users security group', 'Deploy Credential Guard on all endpoints'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'Severe',
    dataCategories: ['IT Systems'],
  },
  {
    id: 'INC-2856',
    title: 'SQL Injection — Customer Database',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1190',
    status: 'Contained',
    detectedAt: null,
    mttd: 1,
    entity: 'api.retailshield.io/v2/customers',
    sourceIP: '45.33.32.156',
    injectionPattern: "' OR 1=1 UNION SELECT",
    suspicionScore: 92,
    description: "SQL injection attack against customer API endpoint. Attacker attempted UNION-based extraction of customer database. WAF blocked 847 injection payloads before successful containment.",
    timeline: [
      { time: '+0:00', event: 'SQL injection attempt detected at /v2/customers endpoint' },
      { time: '+0:01', event: 'WAF triggered — 847 malicious payloads blocked' },
      { time: '+0:01', event: 'Source IP blocked at WAF level' },
    ],
    affectedEntities: ['api.retailshield.io', '45.33.32.156', 'Customer Database'],
    autoDefence: ['WAF rule triggered — payloads blocked', 'Source IP blocked', 'Endpoint rate limited'],
    recommendations: ['Conduct code review of all API endpoints', 'Enable parameterised queries throughout codebase', 'Schedule penetration test of customer-facing APIs'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: ['Customer PII'],
  },
];

export const VULN_FINDINGS = {
  domain: 'demo.retailshield.io',
  scanDate: new Date().toISOString(),
  riskScore: 74,
  summary: { critical: 2, high: 4, medium: 7, low: 5, info: 3 },
  findings: [
    { id: 'VLN-001', severity: 'Critical', category: 'Injection',           title: 'SQL Injection — /api/v2/customers',                  cve: 'CWE-89',  remediation: 'Use parameterised queries or ORM',                    status: 'Pending Review' },
    { id: 'VLN-002', severity: 'Critical', category: 'Injection',           title: 'Stored XSS — Product Review Submission',             cve: 'CWE-79',  remediation: 'Sanitise all user-supplied HTML on write and read',   status: 'Pending Review' },
    { id: 'VLN-003', severity: 'High',     category: 'Authentication',      title: 'Weak Password Policy — No complexity requirement',    cve: 'CWE-521', remediation: 'Enforce minimum 12 chars, symbols, mixed case',       status: 'Open' },
    { id: 'VLN-004', severity: 'High',     category: 'Authentication',      title: 'Missing MFA on Admin Portal',                        cve: 'CWE-308', remediation: 'Enforce TOTP or hardware key for all admin users',    status: 'Open' },
    { id: 'VLN-005', severity: 'High',     category: 'Configuration',       title: 'CORS Misconfiguration — Wildcard Origin',             cve: 'CWE-346', remediation: 'Restrict allowed origins to known domains',           status: 'Open' },
    { id: 'VLN-006', severity: 'High',     category: 'Cryptography',        title: 'TLS 1.0 / 1.1 Enabled on API Gateway',               cve: 'CWE-326', remediation: 'Disable TLS 1.0/1.1; enforce TLS 1.2+',             status: 'Open' },
    { id: 'VLN-007', severity: 'Medium',   category: 'Headers',             title: 'Missing Content-Security-Policy Header',             cve: 'CWE-116', remediation: 'Set restrictive CSP header on all responses',         status: 'Open' },
    { id: 'VLN-008', severity: 'Medium',   category: 'Headers',             title: 'Missing X-Frame-Options (Clickjacking)',             cve: 'CWE-1021',remediation: "Set X-Frame-Options: DENY",                          status: 'Open' },
    { id: 'VLN-009', severity: 'Medium',   category: 'Session Management',  title: 'Session Tokens Not Invalidated on Logout',           cve: 'CWE-613', remediation: 'Implement server-side session invalidation on logout',status: 'Open' },
    { id: 'VLN-010', severity: 'Medium',   category: 'Exposure',            title: 'Server Version Disclosed in HTTP Headers',           cve: 'CWE-200', remediation: 'Remove Server and X-Powered-By headers',             status: 'Open' },
    { id: 'VLN-011', severity: 'Low',      category: 'Cookies',             title: 'Session Cookie Missing Secure Flag',                  cve: 'CWE-614', remediation: 'Set Secure and HttpOnly flags on all session cookies',status: 'Open' },
    { id: 'VLN-012', severity: 'Low',      category: 'Cookies',             title: 'Missing SameSite=Strict on Auth Cookie',             cve: 'CWE-352', remediation: "Set SameSite=Strict on auth cookies",                 status: 'Open' },
    { id: 'VLN-013', severity: 'Info',     category: 'Information',         title: 'robots.txt Discloses Internal Paths',                cve: 'CWE-200', remediation: 'Review robots.txt for sensitive path exposure',        status: 'Info' },
  ],
};

export const COMPLIANCE_REGULATIONS = [
  { id: 'GDPR',   name: 'UK GDPR / Data Protection Act 2018', deadline: '72 hours', authority: 'ICO',  threshold: 'Personal data breach affecting UK data subjects',      status: 'Monitored' },
  { id: 'CSR',    name: 'Cyber Security and Resilience Bill', deadline: '24 hours', authority: 'NCSC', threshold: 'Significant cyber incidents affecting essential services', status: 'Monitored' },
  { id: 'PCI',    name: 'PCI DSS v4.0',                       deadline: '72 hours', authority: 'PCI',  threshold: 'Cardholder data environment incident',                  status: 'Compliant' },
  { id: 'NIS2',   name: 'NIS2 Directive (UK equivalent)',     deadline: '24 hours', authority: 'NCSC', threshold: 'Incidents affecting network and information systems',    status: 'Monitored' },
];

export const SUBMISSION_HISTORY = [
  { id: 'SUB-001', date: '2026-05-22T10:30:00Z', incident: 'INC-2801', regulation: 'UK GDPR', authority: 'ICO',  status: 'Submitted', refNo: 'ICO-2026-051822' },
  { id: 'SUB-002', date: '2026-05-22T08:15:00Z', incident: 'INC-2801', regulation: 'CSR Bill', authority: 'NCSC', status: 'Acknowledged', refNo: 'NCSC-IR-2026-4471' },
  { id: 'SUB-003', date: '2026-04-15T14:22:00Z', incident: 'INC-2764', regulation: 'UK GDPR', authority: 'ICO',  status: 'Closed',    refNo: 'ICO-2026-040122' },
];
