import { C } from './tokens.js';

export const DETECTION_RULES = [
  { id: 'DR-001', name: 'Phishing Email Detection',         technique: 'T1566.001', tactic: 'Initial Access',     severity: 'High',     status: 'Active',   file: 'phishing_detection.kql',        lastTriggered: '2 min ago',   triggerCount: 14 },
  { id: 'DR-002', name: 'Ransomware Indicator',             technique: 'T1486',     tactic: 'Impact',            severity: 'Critical', status: 'Active',   file: 'ransomware_indicator.kql',      lastTriggered: '8 min ago',   triggerCount: 3  },
  { id: 'DR-003', name: 'Data Exfiltration',                technique: 'T1048',     tactic: 'Exfiltration',      severity: 'Critical', status: 'Active',   file: 'data_exfiltration.kql',         lastTriggered: '34 min ago',  triggerCount: 7  },
  { id: 'DR-004', name: 'After-Hours System Access',        technique: 'T1078',     tactic: 'Persistence',       severity: 'Medium',   status: 'Active',   file: 'after_hours_access.kql',        lastTriggered: '1 hr ago',    triggerCount: 21 },
  { id: 'DR-005', name: 'Credential Stuffing',              technique: 'T1110.004', tactic: 'Credential Access', severity: 'High',     status: 'Active',   file: 'credential_stuffing.kql',       lastTriggered: '5 min ago',   triggerCount: 89 },
  { id: 'DR-006', name: 'SQL Injection Attempt',            technique: 'T1190',     tactic: 'Initial Access',    severity: 'High',     status: 'Active',   file: 'sql_injection.kql',             lastTriggered: '12 min ago',  triggerCount: 44 },
  { id: 'DR-007', name: 'Lateral Movement – PtH',          technique: 'T1550.002', tactic: 'Lateral Movement',  severity: 'Critical', status: 'Active',   file: 'lateral_movement.kql',          lastTriggered: '3 hr ago',    triggerCount: 2  },
  { id: 'DR-008', name: 'Privilege Escalation',             technique: 'T1068',     tactic: 'Privilege Escalation', severity: 'High',  status: 'Active',   file: 'priv_escalation.kql',           lastTriggered: '47 min ago',  triggerCount: 9  },
  { id: 'DR-009', name: 'POS Malware Detected',             technique: 'T1055',     tactic: 'Defence Evasion',   severity: 'Critical', status: 'Active',   file: 'pos_malware.kql',               lastTriggered: '1 hr ago',    triggerCount: 1  },
  { id: 'DR-010', name: 'Suspicious PowerShell',            technique: 'T1059.001', tactic: 'Execution',         severity: 'High',     status: 'Active',   file: 'suspicious_powershell.kql',     lastTriggered: '28 min ago',  triggerCount: 17 },
  { id: 'DR-011', name: 'Anomalous Network Traffic',        technique: 'T1071',     tactic: 'C2',                severity: 'Medium',   status: 'Active',   file: 'anomalous_network.kql',         lastTriggered: '6 min ago',   triggerCount: 56 },
  { id: 'DR-012', name: 'Impossible Travel Login',          technique: 'T1078',     tactic: 'Initial Access',    severity: 'High',     status: 'Active',   file: 'impossible_travel.kql',         lastTriggered: '2 hr ago',    triggerCount: 4  },
  { id: 'DR-013', name: 'USB Mass Storage Insert',          technique: 'T1091',     tactic: 'Initial Access',    severity: 'Medium',   status: 'Active',   file: 'usb_insert.kql',                lastTriggered: '4 hr ago',    triggerCount: 11 },
  { id: 'DR-014', name: 'DNS Tunnelling',                   technique: 'T1071.004', tactic: 'C2',                severity: 'High',     status: 'Active',   file: 'dns_tunnel.kql',                lastTriggered: '19 min ago',  triggerCount: 6  },
  { id: 'DR-015', name: 'Supply Chain Compromise',          technique: 'T1195',     tactic: 'Initial Access',    severity: 'Critical', status: 'Active',   file: 'supply_chain.kql',              lastTriggered: '5 hr ago',    triggerCount: 1  },
  { id: 'DR-016', name: 'Brute Force – Admin Panel',        technique: 'T1110.001', tactic: 'Credential Access', severity: 'High',     status: 'Active',   file: 'brute_force_admin.kql',         lastTriggered: '9 min ago',   triggerCount: 33 },
  { id: 'DR-017', name: 'Scheduled Task Creation',          technique: 'T1053.005', tactic: 'Persistence',       severity: 'Medium',   status: 'Active',   file: 'scheduled_task.kql',            lastTriggered: '2 hr ago',    triggerCount: 8  },
  { id: 'DR-018', name: 'LSASS Memory Access',              technique: 'T1003.001', tactic: 'Credential Access', severity: 'Critical', status: 'Active',   file: 'lsass_access.kql',              lastTriggered: '6 hr ago',    triggerCount: 2  },
  { id: 'DR-019', name: 'Malicious Macro in Office File',   technique: 'T1566.001', tactic: 'Initial Access',    severity: 'High',     status: 'Disabled', file: 'office_macro.kql',              lastTriggered: 'Never',       triggerCount: 0  },
  { id: 'LP-001', name: 'POS Void / Refund Abuse',         technique: 'T1657',     tactic: 'Impact',            severity: 'High',     status: 'Active',   file: 'lp-pos-void-refund-abuse.kql',          lastTriggered: '12 min ago',  triggerCount: 7  },
  { id: 'LP-002', name: 'Gift Card Rapid Redemption',      technique: 'T1657',     tactic: 'Impact',            severity: 'High',     status: 'Active',   file: 'lp-gift-card-rapid-redemption.kql',     lastTriggered: '6 min ago',   triggerCount: 3  },
  { id: 'LP-003', name: 'Sweethearting / Buddy Fraud',     technique: 'T1657',     tactic: 'Impact',            severity: 'High',     status: 'Active',   file: 'lp-sweethearting.kql',                  lastTriggered: '2 hr ago',    triggerCount: 2  },
  { id: 'LP-004', name: 'After-Hours POS Transaction',     technique: 'T1657',     tactic: 'Impact',            severity: 'High',     status: 'Active',   file: 'lp-after-hours-pos-transaction.kql',    lastTriggered: '3 hr ago',    triggerCount: 4  },
];

export const MITRE_COVERAGE = [
  { tactic: 'Initial Access',        covered: 5, total: 9  },
  { tactic: 'Execution',             covered: 2, total: 5  },
  { tactic: 'Persistence',           covered: 3, total: 7  },
  { tactic: 'Privilege Escalation',  covered: 2, total: 8  },
  { tactic: 'Defence Evasion',       covered: 3, total: 11 },
  { tactic: 'Credential Access',     covered: 4, total: 9  },
  { tactic: 'Discovery',             covered: 1, total: 7  },
  { tactic: 'Lateral Movement',      covered: 2, total: 4  },
  { tactic: 'Collection',            covered: 1, total: 5  },
  { tactic: 'C2',                    covered: 3, total: 6  },
  { tactic: 'Exfiltration',          covered: 2, total: 4  },
  { tactic: 'Impact',                covered: 4, total: 7  },
];

export const BASELINE_INCIDENTS = [
  {
    id: 'INC-2847', title: 'Credential Stuffing Campaign',
    severity: 'High', tactic: 'Credential Access', technique: 'T1110.004',
    status: 'Investigating', detectedAt: '2026-06-08T09:14:00Z', mttd: 3,
    entity: 'ecom-portal.retailshield.io', sourceIP: '185.220.101.47',
    country: 'Russia', failedAttempts: 1847,
    description: 'Distributed credential stuffing campaign targeting the e-commerce customer portal using breached credential pairs sourced from dark web marketplaces.',
    timeline: [
      { time: '09:11', event: 'First failed login attempt from 185.220.101.47' },
      { time: '09:14', event: 'Alert triggered — 1,847 failed attempts in 15 minutes' },
      { time: '09:16', event: 'IP blocked via automated playbook (block_ip)' },
      { time: '09:22', event: 'SOC analyst began investigation' },
    ],
    affectedEntities: ['ecom-portal.retailshield.io', '185.220.101.47', 'Customer Portal DB'],
    autoDefence: ['Source IP blocked at perimeter firewall', 'Rate limiting applied to /login endpoint', 'CAPTCHA enforcement enabled'],
    recommendations: ['Enable MFA for all customer accounts', 'Implement credential breach monitoring', 'Review and rotate compromised credentials'],
  },
  {
    id: 'INC-2846', title: 'Phishing Email — Invoice Lure',
    severity: 'High', tactic: 'Initial Access', technique: 'T1566.001',
    status: 'Contained', detectedAt: '2026-06-08T08:42:00Z', mttd: 5,
    entity: 'finance@retailshield.io', sourceEmail: 'supplier-invoices@dr4gonmail.com',
    attachmentType: 'docm', phishingScore: 94,
    description: 'Spearphishing email with malicious Word macro attachment delivered to Finance team, spoofing a known supplier domain.',
    timeline: [
      { time: '08:37', event: 'Email received at finance@retailshield.io from dr4gonmail.com' },
      { time: '08:42', event: 'Phishing score 94/100 triggered alert (threshold: 70)' },
      { time: '08:43', event: 'Email quarantined automatically' },
      { time: '08:55', event: 'Attachment analysed — embedded macro with C2 beacon payload' },
    ],
    affectedEntities: ['finance@retailshield.io', 'Finance Department', 'Email Gateway'],
    autoDefence: ['Email quarantined', 'Sender domain blocked', 'Attachment hash added to blocklist'],
    recommendations: ['Conduct phishing awareness training for Finance team', 'Strengthen DMARC/DKIM enforcement', 'Enable macro execution policy via GPO'],
  },
  {
    id: 'INC-2845', title: 'After-Hours POS Access',
    severity: 'Medium', tactic: 'Persistence', technique: 'T1078',
    status: 'Resolved', detectedAt: '2026-06-08T02:17:00Z', mttd: 12,
    entity: 'Store-042', operatorName: 'J. Martins',
    systemAccessed: 'POS', suspicionScore: 72,
    description: 'Employee accessed POS system at Store-042 at 02:17 AM, outside configured operational hours (06:00–22:00).',
    timeline: [
      { time: '02:17', event: 'POS login by J. Martins — outside configured hours' },
      { time: '02:29', event: 'Alert triggered — IsAfterHours flag set' },
      { time: '03:15', event: 'SOC notified store manager' },
      { time: '09:00', event: 'Manager confirmed authorised for stock take — resolved' },
    ],
    affectedEntities: ['Store-042 POS Terminal', 'J. Martins (Employee ID: EMP-3821)'],
    autoDefence: ['SOC notification sent', 'Session flagged for review'],
    recommendations: ['Update after-hours access schedule for planned stock takes', 'Implement manager pre-approval workflow for out-of-hours access'],
  },
];

export const ATTACK_SIM_EVENTS = [
  {
    id: 'INC-2850',
    title: 'DragonForce Ransomware — WAREHOUSE-DC01',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1486',
    status: 'Active',
    detectedAt: null,
    mttd: 2,
    entity: 'WAREHOUSE-DC01',
    deviceName: 'WAREHOUSE-DC01',
    filesModified: 847,
    suspiciousExtension: '.dragon',
    ransomwareFamily: 'DragonForce',
    suspicionScore: 99,
    description: 'DragonForce ransomware detected on warehouse domain controller. 847 files encrypted within 2 minutes of initial execution. Matching M&S supply-chain attack TTP (June 2025).',
    timeline: [
      { time: '+0:00', event: 'Ransomware binary executed on WAREHOUSE-DC01' },
      { time: '+0:02', event: '847 files renamed to .dragon extension' },
      { time: '+0:02', event: 'Alert triggered — FilesModified_d = 847 (threshold: 100)' },
      { time: '+0:03', event: 'Automated endpoint isolation initiated' },
    ],
    affectedEntities: ['WAREHOUSE-DC01', 'Warehouse File Share', 'Domain Controller'],
    autoDefence: ['Endpoint isolated from network', 'Domain admin accounts locked', 'Backup snapshot initiated'],
    recommendations: ['Engage incident response team immediately', 'Notify NCSC within 24 hours (CSR Bill 2025)', 'Notify ICO within 72 hours if personal data affected', 'Assess backup integrity before restoration'],
    needsICO: true,
    needsNCSC: true,
    impactLevel: 'Severe',
    dataCategories: ['Operational Data', 'Employee Records'],
  },
  {
    id: 'INC-2851',
    title: 'Mass Data Exfiltration — Customer Database 2.1TB',
    severity: 'Critical',
    tactic: 'Exfiltration',
    technique: 'T1048',
    status: 'Active',
    detectedAt: null,
    mttd: 4,
    entity: 'ERP-SERVER-01',
    destinationIP: '91.108.4.177',
    destinationPort: 4444,
    dataTransferredGB: 2150,
    geoLocation: 'Russia',
    suspicionScore: 95,
    description: '2.1 TB of data transferred to a Russian-registered IP on port 4444. Data includes customer PII and payment records from ERP system. Possible exfiltration prior to ransomware deployment.',
    timeline: [
      { time: '+0:00', event: 'Outbound connection established to 91.108.4.177:4444' },
      { time: '+0:04', event: '2,150 GB transferred — alert threshold (100 MB) exceeded' },
      { time: '+0:04', event: 'Alert triggered — SuspicionScore_d = 95' },
      { time: '+0:05', event: 'Outbound connection blocked at firewall' },
    ],
    affectedEntities: ['ERP-SERVER-01', '91.108.4.177 (Russia)', 'Customer Database'],
    autoDefence: ['Outbound connection terminated', 'Destination IP added to blocklist', 'DLP policy enforced'],
    recommendations: ['Conduct forensic analysis of ERP-SERVER-01', 'Notify ICO within 72 hours — customer PII likely exfiltrated', 'Engage legal team for breach assessment', 'Review all outbound connections in past 7 days'],
    needsICO: true,
    needsNCSC: true,
    impactLevel: 'Critical',
    dataCategories: ['Customer PII', 'Payment Records', 'Employee Data'],
  },
  {
    id: 'INC-2852',
    title: 'Credential Stuffing — 3,200 Attempts',
    severity: 'High',
    tactic: 'Credential Access',
    technique: 'T1110.004',
    status: 'Active',
    detectedAt: null,
    mttd: 3,
    entity: 'ecom-portal.retailshield.io',
    sourceIP: '185.220.101.52',
    failedAttempts: 3200,
    geoLocation: 'Romania',
    suspicionScore: 90,
    description: 'High-volume credential stuffing attack against customer portal. 3,200 failed login attempts from Romanian IP in 8 minutes using known breached credential pairs.',
    timeline: [
      { time: '+0:00', event: 'Credential stuffing campaign begins from 185.220.101.52' },
      { time: '+0:03', event: 'Alert triggered — 3,200 failed attempts detected' },
      { time: '+0:04', event: 'IP blocked via automated playbook' },
    ],
    affectedEntities: ['ecom-portal.retailshield.io', '185.220.101.52 (Romania)', 'Customer Auth Service'],
    autoDefence: ['Source IP blocked', 'Rate limiting enforced', 'CAPTCHA challenge activated'],
    recommendations: ['Force password reset for potentially affected accounts', 'Enable breach credential monitoring', 'Implement device fingerprinting'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: [],
  },
  {
    id: 'INC-2853',
    title: 'Spearphishing — Finance CFO Targeted',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1566.001',
    status: 'Investigating',
    detectedAt: null,
    mttd: 5,
    entity: 'cfo@retailshield.io',
    sourceEmail: 'board-update@retailshield-plc.co.uk',
    attachmentType: 'xlsm',
    phishingScore: 97,
    description: 'Highly targeted spearphishing email sent to CFO impersonating board communications. XLSM attachment contains obfuscated macro downloading Cobalt Strike beacon.',
    timeline: [
      { time: '+0:00', event: 'Phishing email received at cfo@retailshield.io' },
      { time: '+0:05', event: 'Phishing score 97/100 — immediate quarantine' },
      { time: '+0:06', event: 'Sandbox detonation confirms Cobalt Strike payload' },
    ],
    affectedEntities: ['cfo@retailshield.io', 'Finance Systems', 'Email Gateway'],
    autoDefence: ['Email quarantined', 'Sender domain blocked', 'Macro execution blocked by policy'],
    recommendations: ['Brief CFO on spearphishing TTPs', 'Review email gateway DMARC enforcement', 'Enable advanced threat protection for executive mailboxes'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'High',
    dataCategories: ['Financial Data'],
  },
  {
    id: 'INC-2854',
    title: 'After-Hours ERP Access — Multiple Accounts',
    severity: 'Medium',
    tactic: 'Persistence',
    technique: 'T1078',
    status: 'Investigating',
    detectedAt: null,
    mttd: 8,
    entity: 'ERP-PROD-01',
    operatorName: 'Multiple (4 accounts)',
    systemAccessed: 'ERP',
    suspicionScore: 78,
    description: 'Four employee accounts accessed ERP production system simultaneously at 03:45 AM, outside configured operational hours. Possible insider threat or compromised credentials.',
    timeline: [
      { time: '+0:00', event: '4 concurrent ERP logins at 03:45 AM' },
      { time: '+0:08', event: 'After-hours alert triggered for all 4 accounts' },
      { time: '+0:09', event: 'SOC notification sent to on-call analyst' },
    ],
    affectedEntities: ['ERP-PROD-01', 'Accounts: emp-0192, emp-0341, emp-0088, emp-0612'],
    autoDefence: ['Sessions flagged for review', 'SOC notified', 'Activity logging enhanced'],
    recommendations: ['Interview affected employees', 'Review ERP activity logs for data access', 'Consider suspending accounts pending investigation'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: ['Employee Records', 'Financial Data'],
  },
  {
    id: 'INC-2855',
    title: 'Lateral Movement — Pass-the-Hash Detected',
    severity: 'Critical',
    tactic: 'Lateral Movement',
    technique: 'T1550.002',
    status: 'Active',
    detectedAt: null,
    mttd: 6,
    entity: 'MGMT-SERVER-02',
    sourceHost: 'WAREHOUSE-DC01',
    targetHost: 'MGMT-SERVER-02',
    suspicionScore: 98,
    description: 'Pass-the-hash attack detected moving from compromised WAREHOUSE-DC01 to management server. Attacker using harvested NTLM hashes to authenticate without plaintext credentials.',
    timeline: [
      { time: '+0:00', event: 'Unusual NTLM authentication from WAREHOUSE-DC01 to MGMT-SERVER-02' },
      { time: '+0:06', event: 'Pass-the-hash pattern detected — alert triggered' },
      { time: '+0:07', event: 'Network segmentation enforced between segments' },
    ],
    affectedEntities: ['WAREHOUSE-DC01', 'MGMT-SERVER-02', 'Active Directory'],
    autoDefence: ['Network segment isolated', 'Affected accounts locked', 'Credential reset initiated'],
    recommendations: ['Reset all admin credentials across the domain', 'Enable Protected Users security group', 'Deploy Credential Guard on all endpoints'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'Severe',
    dataCategories: ['IT Systems'],
  },
  {
    id: 'INC-2856',
    title: 'SQL Injection — Customer Database',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1190',
    status: 'Contained',
    detectedAt: null,
    mttd: 1,
    entity: 'api.retailshield.io/v2/customers',
    sourceIP: '45.33.32.156',
    injectionPattern: "' OR 1=1 UNION SELECT",
    suspicionScore: 92,
    description: "SQL injection attack against customer API endpoint. Attacker attempted UNION-based extraction of customer database. WAF blocked 847 injection payloads before successful containment.",
    timeline: [
      { time: '+0:00', event: 'SQL injection attempt detected at /v2/customers endpoint' },
      { time: '+0:01', event: 'WAF triggered — 847 malicious payloads blocked' },
      { time: '+0:01', event: 'Source IP blocked at WAF level' },
    ],
    affectedEntities: ['api.retailshield.io', '45.33.32.156', 'Customer Database'],
    autoDefence: ['WAF rule triggered — payloads blocked', 'Source IP blocked', 'Endpoint rate limited'],
    recommendations: ['Conduct code review of all API endpoints', 'Enable parameterised queries throughout codebase', 'Schedule penetration test of customer-facing APIs'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: ['Customer PII'],
  },
  {
    id: 'INC-2857',
    title: 'Gift Card Drain Attack — 847 Cards in 4 Minutes',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Active',
    detectedAt: null,
    mttd: 4,
    entity: 'giftcard-api.retailshield.io',
    sourceIP: '103.224.182.245',
    cardsAffected: 847,
    estimatedLossGBP: 42350,
    suspicionScore: 93,
    description: 'Automated gift card draining attack — 847 cards balance-checked and redeemed within 4 minutes via the gift card API. Card numbers likely sourced from a prior data breach. Estimated loss £42,350.',
    timeline: [
      { time: '+0:00', event: 'Abnormal gift card API velocity — 200+ balance checks/min' },
      { time: '+0:04', event: 'Alert triggered — 847 cards redeemed in 4 minutes' },
      { time: '+0:05', event: 'Gift card API rate-limited and source IP blocked' },
    ],
    affectedEntities: ['giftcard-api.retailshield.io', '103.224.182.245', '847 gift card accounts'],
    autoDefence: ['Gift card API rate limiting enforced', 'Source IP blocked', 'Affected card numbers frozen'],
    recommendations: ['Freeze and reissue affected gift cards', 'Add CAPTCHA to balance-check endpoint', 'Implement per-card velocity limits', 'Notify affected customers'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'High',
    dataCategories: ['Customer Financial Data'],
  },
  {
    id: 'INC-2858',
    title: 'AI Voice Fraud — Store Manager Impersonation',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1656',
    status: 'Investigating',
    detectedAt: null,
    mttd: 18,
    entity: 'Store-017',
    targetRole: 'Assistant Manager',
    fraudMethod: 'AI voice clone',
    suspicionScore: 88,
    description: 'Assistant manager at Store-017 received a call from an AI-cloned voice impersonating the regional store manager, requesting an emergency cash transfer and till float override. Staff member became suspicious and reported before completing the request.',
    timeline: [
      { time: '+0:00', event: 'Inbound call to Store-017 using cloned voice of regional manager' },
      { time: '+0:12', event: 'Caller requested till override and emergency transfer' },
      { time: '+0:18', event: 'Staff reported via fraud hotline — incident raised' },
    ],
    affectedEntities: ['Store-017', 'Regional Manager (impersonated)', 'Assistant Manager (targeted)'],
    autoDefence: ['Fraud alert broadcast to all stores', 'Verbal-authorisation transfers suspended', 'Call metadata preserved for investigation'],
    recommendations: ['Mandate call-back verification for all financial requests', 'Brief all store managers on AI voice cloning TTPs', 'Establish code-word protocol for high-value authorisations'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: [],
  },
  {
    id: 'INC-2859',
    title: 'POS Void/Refund Manipulation — Staff Insider',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1565',
    status: 'Investigating',
    detectedAt: null,
    mttd: 14,
    entity: 'Store-031',
    operatorName: 'EMP-2204',
    systemAccessed: 'POS',
    voidCount: 38,
    refundTotalGBP: 2870,
    suspicionScore: 85,
    description: 'POS terminal at Store-031 processed 38 void/refund transactions totalling £2,870 in a single shift, all by the same operator and 92% without a customer present (no preceding sale within 30 minutes).',
    timeline: [
      { time: '+0:00', event: 'Void/refund velocity anomaly — 38 transactions in one shift' },
      { time: '+0:14', event: 'Alert triggered — refund-without-sale ratio at 92%' },
      { time: '+0:16', event: 'Operator account flagged and store manager notified' },
    ],
    affectedEntities: ['Store-031 POS Terminal 3', 'EMP-2204', 'Refund ledger'],
    autoDefence: ['Operator POS permissions suspended', 'Manager approval forced for all refunds at Store-031', 'CCTV footage flagged for retention'],
    recommendations: ['Begin HR/loss-prevention investigation', 'Reconcile refund ledger against till takings', 'Require manager PIN for voids above £20'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: ['Financial Data'],
  },
  {
    id: 'INC-2860',
    title: 'Supply Chain Compromise — Supplier Account Abuse',
    severity: 'High',
    tactic: 'Initial Access',
    technique: 'T1199',
    status: 'Active',
    detectedAt: null,
    mttd: 9,
    entity: 'supplier-portal.retailshield.io',
    supplierAccount: 'acme-logistics-ltd',
    sourceIP: '194.5.249.158',
    suspicionScore: 91,
    description: 'Trusted supplier account "acme-logistics-ltd" authenticated from an unrecognised IP in a new country and immediately attempted to modify banking details and download purchase order history — consistent with supplier account takeover.',
    timeline: [
      { time: '+0:00', event: 'Supplier login from 194.5.249.158 — new country, new device' },
      { time: '+0:06', event: 'Attempted change of supplier remittance bank details' },
      { time: '+0:09', event: 'Alert triggered — account suspended pending verification' },
    ],
    affectedEntities: ['supplier-portal.retailshield.io', 'acme-logistics-ltd', 'Accounts Payable'],
    autoDefence: ['Supplier account suspended', 'Bank detail change blocked', 'Accounts Payable notified to hold payments'],
    recommendations: ['Verify with supplier via known contact before reactivation', 'Mandate MFA for all supplier portal accounts', 'Review all supplier bank detail changes in past 30 days'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'High',
    dataCategories: ['Supplier Data', 'Financial Data'],
  },
  {
    id: 'INC-2861',
    title: 'MFA Fatigue Campaign — Finance Team Targeted',
    severity: 'High',
    tactic: 'Credential Access',
    technique: 'T1621',
    status: 'Active',
    detectedAt: null,
    mttd: 7,
    entity: 'finance-team (4 accounts)',
    sourceIP: '45.155.205.99',
    pushCount: 63,
    suspicionScore: 89,
    description: 'Four Finance team accounts received 63 MFA push notifications within 20 minutes from an unrecognised IP — a deliberate MFA fatigue (push bombing) campaign attempting to wear users into approving a fraudulent sign-in.',
    timeline: [
      { time: '+0:00', event: 'Burst of MFA push requests against finance accounts begins' },
      { time: '+0:07', event: 'Alert triggered — 63 pushes across 4 accounts in 20 minutes' },
      { time: '+0:08', event: 'Push approvals disabled; number-matching MFA enforced' },
    ],
    affectedEntities: ['4 Finance team accounts', '45.155.205.99', 'Azure AD'],
    autoDefence: ['MFA push approvals disabled for targeted accounts', 'Sign-in risk policy escalated', 'Source IP blocked'],
    recommendations: ['Move all users to number-matching MFA', 'Reset passwords for the 4 targeted accounts', 'Brief Finance team on MFA fatigue tactics'],
    needsICO: false,
    needsNCSC: false,
    impactLevel: 'Moderate',
    dataCategories: [],
  },
  {
    id: 'INC-2862',
    title: 'Privileged Role Addition — Silent Persistence',
    severity: 'High',
    tactic: 'Persistence',
    technique: 'T1098.003',
    status: 'Active',
    detectedAt: null,
    mttd: 11,
    entity: 'Azure AD',
    accountModified: 'svc-backup-02',
    roleAdded: 'Global Administrator',
    suspicionScore: 94,
    description: 'Service account "svc-backup-02" was silently granted Global Administrator outside change control, from a session originating on a previously compromised host — a classic persistence mechanism to survive credential resets.',
    timeline: [
      { time: '+0:00', event: 'Global Administrator role assigned to svc-backup-02' },
      { time: '+0:11', event: 'Alert triggered — privileged role change outside change window' },
      { time: '+0:12', event: 'Role assignment reverted; account disabled' },
    ],
    affectedEntities: ['svc-backup-02', 'Azure AD tenant', 'Privileged Identity Management'],
    autoDefence: ['Role assignment automatically reverted', 'Service account disabled', 'All privileged role changes frozen pending review'],
    recommendations: ['Audit all role assignments in the past 30 days', 'Enable PIM just-in-time access for all admin roles', 'Alert on any standing Global Administrator additions'],
    needsICO: false,
    needsNCSC: true,
    impactLevel: 'High',
    dataCategories: ['IT Systems'],
  },
];

export const VULN_FINDINGS = {
  domain: 'demo.retailshield.io',
  scanDate: new Date().toISOString(),
  riskScore: 74,
  summary: { critical: 2, high: 4, medium: 4, low: 3, info: 3 },
  findings: [
    { id: 'VLN-001', severity: 'Critical', category: 'Injection',       title: 'SQL Injection — /api/v2/customers',                       cve: 'CWE-89',        remediation: 'Use parameterised queries or a type-safe ORM throughout the codebase. Never concatenate user input into SQL strings.',                        status: 'Pending Review' },
    { id: 'VLN-002', severity: 'Critical', category: 'Injection',       title: 'Stored XSS — Product Review Submission',                  cve: 'CWE-79',        remediation: 'HTML-encode all user-supplied content on write and escape on read. Apply a Content Security Policy to restrict inline script execution.',   status: 'Pending Review' },
    { id: 'VLN-003', severity: 'High',     category: 'Authentication',  title: 'Weak Password Policy — No Complexity Requirement',        cve: 'CWE-521',       remediation: 'Enforce a minimum of 12 characters with at least one uppercase letter, one lowercase letter, one digit, and one special character.',         status: 'Open' },
    { id: 'VLN-004', severity: 'High',     category: 'Authentication',  title: 'Missing MFA on Admin Portal',                             cve: 'CWE-308',       remediation: 'Enforce TOTP or a FIDO2 hardware key for all admin accounts. Deny access to the portal without a second factor.',                           status: 'Open' },
    { id: 'VLN-005', severity: 'High',     category: 'Exposure',        title: 'Server Version Disclosure — Apache 2.4.51',               cve: 'CVE-2021-42013', remediation: 'Set ServerTokens Prod in Apache config to suppress version disclosure. Remove X-Powered-By and Server headers at the reverse proxy.',      status: 'Open' },
    { id: 'VLN-006', severity: 'High',     category: 'Dependencies',    title: 'Unpatched jQuery 1.12.4 — CVE-2020-11022',                cve: 'CVE-2020-11022', remediation: 'Upgrade jQuery to 3.7.1 or later. Run npm audit and address all high/critical findings in the dependency tree.',                             status: 'Open' },
    { id: 'VLN-007', severity: 'Medium',   category: 'Headers',         title: 'Missing Content Security Policy Header',                  cve: 'CWE-116',       remediation: "Set a restrictive Content-Security-Policy header on all responses. Start with default-src 'self' and expand only as required.",              status: 'Open' },
    { id: 'VLN-008', severity: 'Medium',   category: 'Configuration',   title: 'HTTP to HTTPS Redirect Not Enforced on /checkout',        cve: 'CWE-319',       remediation: 'Redirect all HTTP traffic to HTTPS via 301. Add Strict-Transport-Security: max-age=31536000; includeSubDomains; preload.',                   status: 'Open' },
    { id: 'VLN-009', severity: 'Medium',   category: 'Cookies',         title: 'Session Cookie Missing Secure Flag (session_id)',          cve: 'CWE-614',       remediation: 'Set the Secure and HttpOnly flags on the session_id cookie so it is only transmitted over HTTPS and is inaccessible to JavaScript.',         status: 'Open' },
    { id: 'VLN-010', severity: 'Medium',   category: 'Configuration',   title: 'CORS Wildcard Misconfiguration',                          cve: 'CWE-346',       remediation: 'Replace Access-Control-Allow-Origin: * with an explicit allowlist of trusted origins. Reject requests from unlisted origins at the gateway.', status: 'Open' },
    { id: 'VLN-011', severity: 'Low',      category: 'Headers',         title: 'Missing X-Frame-Options Header',                          cve: 'CWE-1021',      remediation: "Set X-Frame-Options: DENY on all responses to prevent clickjacking. Alternatively, use Content-Security-Policy: frame-ancestors 'none'.",  status: 'Open' },
    { id: 'VLN-012', severity: 'Low',      category: 'Exposure',        title: 'Server Timezone Disclosed in HTTP Headers',               cve: 'CWE-200',       remediation: 'Remove the Date header or normalise it to UTC. Suppress any server-side timezone disclosure in response headers and error pages.',           status: 'Open' },
    { id: 'VLN-013', severity: 'Low',      category: 'Configuration',   title: 'Directory Listing Enabled on /assets/',                   cve: 'CWE-548',       remediation: 'Disable directory listing in the web server configuration (Options -Indexes in Apache; autoindex off in nginx).',                            status: 'Open' },
    { id: 'VLN-014', severity: 'Info',     category: 'Certificate',     title: 'SSL Certificate Expires in 47 Days',                      cve: '—',             remediation: 'Renew the TLS certificate before expiry. Consider automating renewal with ACME / Let\'s Encrypt or AWS Certificate Manager.',               status: 'Info' },
    { id: 'VLN-015', severity: 'Info',     category: 'Configuration',   title: 'TLS 1.0 Still Supported (Deprecated)',                    cve: 'CWE-326',       remediation: 'Disable TLS 1.0 and TLS 1.1 at the load balancer or API gateway. Enforce TLS 1.2 as the minimum; prefer TLS 1.3.',                          status: 'Info' },
    { id: 'VLN-016', severity: 'Info',     category: 'Headers',         title: 'Missing Referrer-Policy Header',                          cve: 'CWE-116',       remediation: 'Set Referrer-Policy: no-referrer-when-downgrade on all responses to prevent leaking URLs to third-party domains via the Referer header.',  status: 'Info' },
  ],
};

export const COMPLIANCE_REGULATIONS = [
  { id: 'GDPR',   name: 'UK GDPR / Data Protection Act 2018', deadline: '72 hours', authority: 'ICO',  threshold: 'Personal data breach affecting UK data subjects',      status: 'Monitored' },
  { id: 'CSR',    name: 'Cyber Security and Resilience Bill', deadline: '24 hours', authority: 'NCSC', threshold: 'Significant cyber incidents affecting essential services', status: 'Monitored' },
  { id: 'PCI',    name: 'PCI DSS v4.0',                       deadline: '72 hours', authority: 'PCI',  threshold: 'Cardholder data environment incident',                  status: 'Compliant' },
  { id: 'NIS2',   name: 'NIS2 Directive (UK equivalent)',     deadline: '24 hours', authority: 'NCSC', threshold: 'Incidents affecting network and information systems',    status: 'Monitored' },
];

export const LP_INCIDENTS = [
  {
    id: 'LP-INC-001',
    title: 'High-Volume Void Abuse — Store-031 Cashier',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Investigating',
    detectedAt: '2026-06-21T11:42:00Z',
    mttd: 3,
    ruleId: 'LP-001',
    detectionSignal: 'HighVolumeVoidRefund',
    storeId: 'Store-031',
    operatorId: 'EMP-2204',
    terminalId: 'POS-031-03',
    transactionCount: 14,
    totalValueGBP: 847.50,
    hasManagerOverride: false,
    riskScore: 80,
    description: 'Cashier EMP-2204 processed 14 void/refund transactions totalling £847.50 in a 30-minute window at Store-031 — exceeding the threshold of 10 per window with no manager override recorded.',
    timeline: [
      { time: '11:09', event: 'First void transaction processed by EMP-2204 at POS-031-03' },
      { time: '11:39', event: '14th void in 30-minute window — HighVolumeVoidRefund threshold crossed' },
      { time: '11:42', event: 'Alert triggered — lp-incident-response playbook invoked' },
      { time: '11:44', event: 'Store manager notified; POS permissions suspended pending review' },
    ],
    affectedEntities: ['EMP-2204', 'POS-031-03', 'Store-031 till ledger'],
    autoDefence: ['POS operator account suspended', 'Store manager alerted', 'CCTV timestamp flagged for review'],
    recommendations: ['Reconcile void transactions against customer receipts', 'Require manager PIN for all voids above £20', 'Begin HR investigation if reconciliation fails'],
    estimatedLossGBP: 847.50,
  },
  {
    id: 'LP-INC-002',
    title: 'Critical Value Void — No Override — Store-017',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Active',
    detectedAt: '2026-06-21T14:08:00Z',
    mttd: 1,
    ruleId: 'LP-001',
    detectionSignal: 'HighValueVoidNoOverride',
    storeId: 'Store-017',
    operatorId: 'EMP-0891',
    terminalId: 'POS-017-01',
    transactionCount: 3,
    totalValueGBP: 1240.00,
    hasManagerOverride: false,
    riskScore: 95,
    description: 'Three high-value void transactions totalling £1,240 processed at Store-017 POS-017-01 by EMP-0891 with no manager override recorded. Total exceeds the £500 Critical threshold.',
    timeline: [
      { time: '14:01', event: 'First high-value void — £420.00 — no override on POS-017-01' },
      { time: '14:05', event: 'Second void — £380.00' },
      { time: '14:07', event: 'Third void — £440.00 — total reaches £1,240' },
      { time: '14:08', event: 'Critical alert fired — HighValueVoidNoOverride, RiskScore 95' },
    ],
    affectedEntities: ['EMP-0891', 'POS-017-01', 'Store-017 refund ledger'],
    autoDefence: ['Operator account suspended immediately', 'Manager PIN enforcement activated at terminal', 'Incident escalated to Loss Prevention team'],
    recommendations: ['Conduct same-day investigation and reconciliation', 'Review 7-day void history for EMP-0891', 'Preserve CCTV footage for the 14:00–14:10 window'],
    estimatedLossGBP: 1240.00,
  },
  {
    id: 'LP-INC-003',
    title: 'Bulk Gift Card Activation — 12 Cards in 40 Minutes',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Investigating',
    detectedAt: '2026-06-21T10:22:00Z',
    mttd: 6,
    ruleId: 'LP-002',
    detectionSignal: 'BulkGiftCardActivation',
    storeId: 'Store-008',
    operatorId: 'EMP-1155',
    terminalId: 'POS-008-02',
    activationCount: 12,
    totalValueGBP: 600.00,
    riskScore: 80,
    description: 'EMP-1155 activated 12 gift cards totalling £600 in a 40-minute window at Store-008 — more than double the BulkActivationThresh of 5. No matching customer loyalty transactions recorded.',
    timeline: [
      { time: '09:42', event: 'First gift card activated by EMP-1155 on POS-008-02' },
      { time: '10:01', event: 'Fifth card activated — BulkActivationThresh reached' },
      { time: '10:22', event: 'Twelfth card activated — alert triggered' },
      { time: '10:28', event: 'Gift card activation capability suspended at terminal' },
    ],
    affectedEntities: ['EMP-1155', 'POS-008-02', '12 gift card accounts (GC-batch-9821xx)'],
    autoDefence: ['Gift card activation suspended at POS-008-02', 'Card batch flagged in gift card system', 'Store manager notified'],
    recommendations: ['Freeze the 12 activated cards pending investigation', 'Verify activation purpose with EMP-1155 and store manager', 'Cross-check cards against customer purchase records'],
    estimatedLossGBP: 600.00,
  },
  {
    id: 'LP-INC-004',
    title: 'Rapid Cross-Store Gift Card Redemption — Organised Fraud',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Active',
    detectedAt: '2026-06-20T16:14:00Z',
    mttd: 4,
    ruleId: 'LP-002',
    detectionSignal: 'RapidCrossChannelRedemption',
    storeId: 'Store-003',
    operatorId: 'EMP-0312',
    terminalId: 'POS-003-01',
    activationCount: 8,
    totalValueGBP: 480.00,
    minutesSinceActivation: 18,
    riskScore: 90,
    description: '8 gift cards activated at Store-003 were redeemed online within 18 minutes of activation — well within the 30-minute cross-channel threshold. Consistent with organised gift card fraud using stolen card numbers.',
    timeline: [
      { time: '15:52', event: '8 gift cards activated at Store-003 POS-003-01 by EMP-0312' },
      { time: '16:10', event: 'All 8 cards redeemed via online channel within 18 minutes of activation' },
      { time: '16:14', event: 'RapidCrossChannelRedemption alert fired — Critical, RiskScore 90' },
      { time: '16:15', event: 'Cards suspended; online redemption channel flagged' },
    ],
    affectedEntities: ['EMP-0312', 'POS-003-01', '8 gift card accounts', 'Online redemption API'],
    autoDefence: ['Affected cards frozen', 'Online channel velocity limit applied', 'Fraud team alerted'],
    recommendations: ['Coordinate with online fraud team to trace redemption session', 'Investigate whether EMP-0312 acted alone or with an accomplice', 'Consider law enforcement referral if organised crime suspected'],
    estimatedLossGBP: 480.00,
  },
  {
    id: 'LP-INC-005',
    title: 'Sweethearting — Cashier Serving Same Customer 9 Times at 38% Discount',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Investigating',
    detectedAt: '2026-06-21T06:00:00Z',
    mttd: 22,
    ruleId: 'LP-003',
    detectionSignal: 'RepeatHighDiscountRelationship',
    storeId: 'Store-042',
    operatorId: 'EMP-3301',
    loyaltyCardId: 'LC-88821934',
    transactionCount: 9,
    avgDiscountRate: 0.38,
    totalDiscountGBP: 314.20,
    avgBasketGBP: 36.84,
    riskScore: 75,
    description: 'Cashier EMP-3301 served loyalty customer LC-88821934 nine times over 7 days with an average discount of 38% — substantially above the 30% threshold. No loyalty programme entitlement found for the customer profile.',
    timeline: [
      { time: 'Day 1', event: 'First transaction flagged — 41% discount applied by EMP-3301' },
      { time: 'Days 2–6', event: '8 further transactions — all with discounts between 32% and 44%' },
      { time: 'Day 7 06:00', event: '7-day rolling analysis triggered RepeatHighDiscountRelationship alert' },
      { time: 'Day 7 06:22', event: 'Loss prevention manager notified; HR review scheduled' },
    ],
    affectedEntities: ['EMP-3301', 'LC-88821934 (loyalty customer)', 'Store-042 discount ledger'],
    autoDefence: ['Discount cap applied to EMP-3301 terminal pending review', 'LP manager alerted', 'Transaction history exported for HR'],
    recommendations: ['Conduct full 30-day discount audit for EMP-3301', 'Cross-check LC-88821934 loyalty entitlement', 'Review CCTV to confirm whether all items were scanned'],
    estimatedLossGBP: 314.20,
  },
  {
    id: 'LP-INC-006',
    title: 'Discount Concentration — Cashier Responsible for 52% of Terminal Discounts',
    severity: 'High',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Investigating',
    detectedAt: '2026-06-20T06:00:00Z',
    mttd: 31,
    ruleId: 'LP-003',
    detectionSignal: 'HighDiscountConcentrationAtTerminal',
    storeId: 'Store-019',
    operatorId: 'EMP-0774',
    terminalId: 'POS-019-04',
    discountShare: 0.52,
    totalDiscountGBP: 892.60,
    riskScore: 70,
    description: 'Cashier EMP-0774 was responsible for 52% of all discounts issued at POS-019-04 over the past 7 days — more than double the DiscountShareThresh of 40%. Peer comparison shows the terminal average is 11% per operator.',
    timeline: [
      { time: 'Day 1–7', event: 'EMP-0774 discount share accumulates to 52% of POS-019-04 total' },
      { time: 'Day 7 06:00', event: '7-day analysis triggers HighDiscountConcentrationAtTerminal signal' },
      { time: 'Day 7 06:31', event: 'LP manager notified; discount activity review initiated' },
    ],
    affectedEntities: ['EMP-0774', 'POS-019-04', 'Store-019 discount ledger'],
    autoDefence: ['LP manager alerted', 'Discount log exported for peer comparison', 'Terminal flagged for enhanced monitoring'],
    recommendations: ['Compare EMP-0774 basket values against terminal peers', 'Audit discount transactions for items not appearing on receipt', 'Consider covert observation if pattern continues'],
    estimatedLossGBP: 892.60,
  },
  {
    id: 'LP-INC-007',
    title: 'Ghost Employee — After-Hours POS Access — Store-007',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Active',
    detectedAt: '2026-06-21T02:31:00Z',
    mttd: 2,
    ruleId: 'LP-004',
    detectionSignal: 'GhostEmployeeAfterHours',
    storeId: 'Store-007',
    operatorId: 'EMP-9901',
    terminalId: 'POS-007-02',
    transactionCount: 4,
    totalValueGBP: 612.00,
    hourOfDay: 2,
    riskScore: 92,
    description: 'Operator EMP-9901 processed 4 transactions totalling £612 at Store-007 at 02:31 AM — outside trading hours (06:00–22:00). No daytime shift record exists for EMP-9901 in the past 24 hours, matching the GhostEmployee pattern.',
    timeline: [
      { time: '02:27', event: 'EMP-9901 logs into POS-007-02 — no active shift record in system' },
      { time: '02:31', event: '4 transactions processed totalling £612.00' },
      { time: '02:31', event: 'GhostEmployeeAfterHours alert fired — Critical, RiskScore 92' },
      { time: '02:33', event: 'Terminal locked remotely; security team alerted' },
    ],
    affectedEntities: ['EMP-9901', 'POS-007-02', 'Store-007 till'],
    autoDefence: ['Terminal remotely locked', 'Security team dispatched', 'EMP-9901 credential suspended'],
    recommendations: ['Contact on-site security and review CCTV immediately', 'Verify whether EMP-9901 badge access records confirm physical presence', 'Consider law enforcement notification if unauthorised entry is confirmed'],
    estimatedLossGBP: 612.00,
  },
  {
    id: 'LP-INC-008',
    title: 'Closed-Store Terminal Burst — 5 Transactions Outside Hours',
    severity: 'Critical',
    tactic: 'Impact',
    technique: 'T1657',
    status: 'Investigating',
    detectedAt: '2026-06-20T23:58:00Z',
    mttd: 4,
    ruleId: 'LP-004',
    detectionSignal: 'ClosedStoreTerminalBurst',
    storeId: 'Store-022',
    operatorId: 'EMP-4417',
    terminalId: 'POS-022-01',
    transactionCount: 5,
    totalValueGBP: 388.75,
    hourOfDay: 23,
    riskScore: 92,
    description: '5 POS transactions processed at POS-022-01 in a 30-minute window starting at 23:50 — after the 22:00 store close. The terminal burst of 5 exceeds the ClosedStoreTerminalBurst threshold of 3.',
    timeline: [
      { time: '23:50', event: 'First after-hours transaction on POS-022-01' },
      { time: '23:54', event: 'Third transaction — TerminalBurstThresh crossed' },
      { time: '23:58', event: 'ClosedStoreTerminalBurst alert — Critical, RiskScore 92' },
      { time: '00:02', event: 'Store manager contacted; badge access audit initiated' },
    ],
    affectedEntities: ['EMP-4417', 'POS-022-01', 'Store-022 after-hours log'],
    autoDefence: ['Terminal flagged; manager notified', 'Badge access log pulled for Store-022', 'Activity flagged for LP review'],
    recommendations: ['Correlate transactions with badge entry records', 'Review CCTV footage at store entrance from 23:40 onwards', 'Determine if authorised (stock count) or investigate as till manipulation'],
    estimatedLossGBP: 388.75,
  },
];

export const LP_STORE_RISK = [
  { storeId: 'Store-007', storeName: 'Oxford Street',    riskScore: 92, openIncidents: 1, highestSignal: 'GhostEmployeeAfterHours',        lastIncident: '2026-06-21T02:31:00Z', trend: 'up'   },
  { storeId: 'Store-017', storeName: 'Canary Wharf',     riskScore: 88, openIncidents: 1, highestSignal: 'HighValueVoidNoOverride',         lastIncident: '2026-06-21T14:08:00Z', trend: 'up'   },
  { storeId: 'Store-003', storeName: 'Westfield Strat.', riskScore: 84, openIncidents: 1, highestSignal: 'RapidCrossChannelRedemption',     lastIncident: '2026-06-20T16:14:00Z', trend: 'up'   },
  { storeId: 'Store-022', storeName: 'Bluewater',        riskScore: 80, openIncidents: 1, highestSignal: 'ClosedStoreTerminalBurst',        lastIncident: '2026-06-20T23:58:00Z', trend: 'stable'},
  { storeId: 'Store-031', storeName: 'Trafford Centre',  riskScore: 74, openIncidents: 1, highestSignal: 'HighVolumeVoidRefund',            lastIncident: '2026-06-21T11:42:00Z', trend: 'stable'},
  { storeId: 'Store-042', storeName: 'Meadowhall',       riskScore: 68, openIncidents: 1, highestSignal: 'RepeatHighDiscountRelationship',  lastIncident: '2026-06-21T06:00:00Z', trend: 'up'   },
  { storeId: 'Store-019', storeName: 'Bullring',         riskScore: 62, openIncidents: 1, highestSignal: 'HighDiscountConcentrationAtTerminal', lastIncident: '2026-06-20T06:00:00Z', trend: 'stable'},
  { storeId: 'Store-008', storeName: 'Brent Cross',      riskScore: 58, openIncidents: 1, highestSignal: 'BulkGiftCardActivation',          lastIncident: '2026-06-21T10:22:00Z', trend: 'down' },
  { storeId: 'Store-011', storeName: 'Lakeside',         riskScore: 28, openIncidents: 0, highestSignal: null,                              lastIncident: null,                    trend: 'stable'},
  { storeId: 'Store-055', storeName: 'Arndale',          riskScore: 21, openIncidents: 0, highestSignal: null,                              lastIncident: null,                    trend: 'down' },
];

export const SUBMISSION_HISTORY = [
  { id: 'SUB-001', date: '2026-05-22T10:30:00Z', incident: 'INC-2801', regulation: 'UK GDPR', authority: 'ICO',  status: 'Submitted', refNo: 'ICO-2026-051822' },
  { id: 'SUB-002', date: '2026-05-22T08:15:00Z', incident: 'INC-2801', regulation: 'CSR Bill', authority: 'NCSC', status: 'Acknowledged', refNo: 'NCSC-IR-2026-4471' },
  { id: 'SUB-003', date: '2026-04-15T14:22:00Z', incident: 'INC-2764', regulation: 'UK GDPR', authority: 'ICO',  status: 'Closed',    refNo: 'ICO-2026-040122' },
];
